package com.smithyhono.writers;

import com.smithyhono.ModelIndex;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.*;
import software.amazon.smithy.model.traits.HttpHeaderTrait;
import software.amazon.smithy.model.traits.HttpPrefixHeadersTrait;
import software.amazon.smithy.model.traits.HttpQueryTrait;
import software.amazon.smithy.model.traits.HttpTrait;

import java.util.*;

/**
 * Emits a typed, binding-aware {@code fetch} client ({@code <stem>.client.gen.ts})
 * alongside the router. The SAME generator emits both server and client, so the wire
 * contract (path/query/header/body bindings, status codes, error shapes) agrees by
 * construction — no protocol-conformance gap.
 *
 * <p>The client uses only Web-standard APIs ({@code fetch}/{@code Headers}/
 * {@code URLSearchParams}) — no new npm dependency, ARCH-01 preserved. In tests you
 * pass {@code app.request.bind(app)} as the {@code fetch}; in production you pass
 * {@code globalThis.fetch} + a {@code baseUrl}.
 */
public class ClientEmitter {
    private final Model model;
    private final ModelIndex index;

    public ClientEmitter(Model model, ModelIndex index) {
        this.model = model;
        this.index = index;
    }

    /**
     * Emits the entire client file for one resource group.
     *
     * @param groupName      the resource group name (e.g. {@code "Todo"})
     * @param stem           the kebab-case file stem (e.g. {@code "todo"})
     * @param ops            the group's HTTP operations
     * @param errors         the error structures emitted in {@code <stem>.gen.ts}
     *                       (service errors first), reused for typed error mapping
     * @param sharedShapeIds shapes emitted to {@code shared.gen.ts} (import routing)
     */
    public void emitClientFile(String groupName, String stem, List<OperationShape> ops,
                               List<StructureShape> errors, Set<ShapeId> sharedShapeIds,
                               TypeScriptFileWriter writer) {
        emitClientFile(groupName, stem, ops, errors, sharedShapeIds, java.util.Set.of(), writer);
    }

    /**
     * @param sharedShapeIds shapes emitted to {@code shared.gen.ts} (import routing)
     * @param sharedErrorIds error classes emitted to {@code errors.gen.ts} (import routing)
     */
    public void emitClientFile(String groupName, String stem, List<OperationShape> ops,
                               List<StructureShape> errors, Set<ShapeId> sharedShapeIds,
                               Set<ShapeId> sharedErrorIds, TypeScriptFileWriter writer) {
        String factoryName = "create" + groupName + "Client";
        String clientType = groupName + "Client";
        String optsType = groupName + "ClientOptions";

        writer.comment("DO NOT EDIT — regenerated by smithy-hono on every build");
        writer.blank();

        emitImports(stem, ops, errors, sharedShapeIds, sharedErrorIds, writer);

        writer.comment("---- Client options ----");
        writer.blank();
        writer.line("export interface " + optsType + " {");
        writer.line("  /** Defaults to globalThis.fetch. In tests pass app.request.bind(app). */");
        writer.line("  fetch?: FetchLike");
        writer.line("  /** Prepended to every request path (e.g. 'https://api.example.com'). Defaults to ''. */");
        writer.line("  baseUrl?: string");
        writer.line("  /** Headers merged into every request — cookies / CSRF / signing. Awaited per request. */");
        writer.line("  headers?: () => HeadersInit | Promise<HeadersInit>");
        writer.line("}");
        writer.blank();

        writer.comment("---- Client interface ----");
        writer.blank();
        writer.line("export interface " + clientType + " {");
        for (OperationShape op : ops) {
            String name = op.getId().getName();
            String input = OperationTypes.inputType(model, index, op);
            String output = OperationTypes.outputType(index, op);
            writer.line("  " + name + "(input: " + input + "): Promise<" + output + ">");
        }
        writer.line("}");
        writer.blank();

        emitHelpers(errors, writer);

        writer.comment("---- Client factory ----");
        writer.blank();
        writer.line("export function " + factoryName + "(opts: " + optsType + " = {}): " + clientType + " {");
        writer.line("  const _fetch: FetchLike = opts.fetch ?? globalThis.fetch");
        writer.line("  const _base = opts.baseUrl ?? ''");
        writer.line("  const _headers = opts.headers ?? (() => ({}))");
        writer.line("  return {");
        for (OperationShape op : ops) {
            emitMethod(op, writer);
        }
        writer.line("  }");
        writer.line("}");
    }

    // ── Imports ────────────────────────────────────────────────────────────────

    private void emitImports(String stem, List<OperationShape> ops, List<StructureShape> errors,
                             Set<ShapeId> sharedShapeIds, Set<ShapeId> sharedErrorIds,
                             TypeScriptFileWriter writer) {
        Set<String> errorNames = new LinkedHashSet<>();
        for (StructureShape e : errors) errorNames.add(e.getId().getName());

        // Named I/O types referenced in the method signatures, routed to their file.
        Set<String> localTypes = new LinkedHashSet<>();
        Set<String> sharedTypes = new LinkedHashSet<>();
        for (OperationShape op : ops) {
            for (ShapeId id : OperationTypes.referencedNamedTypes(model, index, op)) {
                String name = id.getName();
                if (errorNames.contains(name)) continue; // imported as a value below
                if (sharedShapeIds.contains(id)) sharedTypes.add(name);
                else localTypes.add(name);
            }
        }

        // Error CLASSES are routed by whether they were hoisted to errors.gen.ts (shared by 2+
        // groups) or stayed in this group's ./<stem>.gen, matching the router file's emission.
        Set<String> localErrorNames = new LinkedHashSet<>();
        Set<String> sharedErrorNames = new LinkedHashSet<>();
        for (StructureShape e : errors) {
            if (sharedErrorIds.contains(e.getId())) sharedErrorNames.add(e.getId().getName());
            else localErrorNames.add(e.getId().getName());
        }

        if (!localTypes.isEmpty()) {
            writer.line("import type { " + String.join(", ", localTypes) + " } from './" + stem + ".gen'");
        }
        if (!sharedTypes.isEmpty()) {
            writer.line("import type { " + String.join(", ", sharedTypes) + " } from './shared.gen'");
        }
        if (!localErrorNames.isEmpty()) {
            writer.line("import { " + String.join(", ", localErrorNames) + " } from './" + stem + ".gen'");
        }
        if (!sharedErrorNames.isEmpty()) {
            writer.line("import { " + String.join(", ", sharedErrorNames) + " } from './errors.gen'");
        }
        writer.line("import type { FetchLike } from './client-runtime.gen'");
        writer.line("import { SmithyError } from './errors'");
        writer.blank();
    }

    // ── Shared helpers (one set per file) ───────────────────────────────────────

    private void emitHelpers(List<StructureShape> errors, TypeScriptFileWriter writer) {
        writer.comment("---- Internal helpers ----");
        writer.blank();
        writer.line("async function _readBody(res: Response): Promise<unknown> {");
        writer.line("  const text = await res.text()");
        writer.line("  return text ? JSON.parse(text) : undefined");
        writer.line("}");
        writer.blank();
        // Map a non-2xx response back to the SAME generated error classes the server
        // throws (discriminated by the `code` body field — restJson1-style), falling
        // back to SmithyError for unmodeled responses (generic 500, validation 400).
        writer.line("function _throwError(status: number, body: unknown): never {");
        writer.line("  const b = (body ?? {}) as { code?: string; message?: string; fieldErrors?: unknown }");
        writer.line("  const message = b.message");
        writer.line("    ?? (b.fieldErrors !== undefined ? 'ValidationException: ' + JSON.stringify(b.fieldErrors) : 'HTTP ' + status)");
        if (!errors.isEmpty()) {
            writer.line("  switch (b.code) {");
            for (StructureShape e : errors) {
                String name = e.getId().getName();
                writer.line("    case '" + name + "': throw new " + name + "(message)");
            }
            writer.line("  }");
        }
        writer.line("  throw new SmithyError(message, status, status >= 500 ? 'server' : 'client')");
        writer.line("}");
        writer.blank();
    }

    // ── Per-operation method ────────────────────────────────────────────────────

    private void emitMethod(OperationShape op, TypeScriptFileWriter writer) {
        HttpTrait http = op.expectTrait(HttpTrait.class);
        String name = op.getId().getName();
        String method = http.getMethod();
        String uri = http.getUri().toString();

        InputBindings b = index.getInput(op)
            .map(in -> new InputBindings(in, method))
            .orElse(null);
        boolean hasOutput = index.getOutput(op).map(o -> !o.getAllMembers().isEmpty()).orElse(false);
        boolean hasBody = b != null && !b.bodyMembers.isEmpty();

        writer.line("    async " + name + "(input) {");
        writer.line("      const headers = new Headers(await _headers())");

        // Header bindings.
        if (b != null) {
            for (Map.Entry<String, MemberShape> e : b.headerMembers.entrySet()) {
                String wire = e.getValue().expectTrait(HttpHeaderTrait.class).getValue();
                writer.line("      if (input." + e.getKey() + " !== undefined) headers.set("
                    + TypeScriptFileWriter.stringLiteral(wire) + ", String(input." + e.getKey() + "))");
            }
            for (Map.Entry<String, MemberShape> e : b.prefixHeadersMembers.entrySet()) {
                String prefix = e.getValue().expectTrait(HttpPrefixHeadersTrait.class).getValue();
                writer.line("      for (const [k, v] of Object.entries(input." + e.getKey()
                    + " ?? {})) headers.set(" + TypeScriptFileWriter.stringLiteral(prefix) + " + k, String(v))");
            }
        }
        if (hasBody) {
            writer.line("      headers.set('content-type', 'application/json')");
        }

        // Path (label substitution) + query string.
        String pathTemplate = buildPathTemplate(uri, b);
        boolean hasQuery = b != null && (!b.queryMembers.isEmpty() || !b.queryParamsMembers.isEmpty());
        String urlExpr;
        if (hasQuery) {
            writer.line("      const _q = new URLSearchParams()");
            for (Map.Entry<String, MemberShape> e : b.queryMembers.entrySet()) {
                String memberName = e.getKey();
                MemberShape member = e.getValue();
                String wire = member.getTrait(HttpQueryTrait.class).map(HttpQueryTrait::getValue).orElse(memberName);
                Shape target = model.expectShape(member.getTarget());
                if (target.isListShape()) {
                    writer.line("      for (const v of input." + memberName + " ?? []) _q.append("
                        + TypeScriptFileWriter.stringLiteral(wire) + ", String(v))");
                } else {
                    writer.line("      if (input." + memberName + " !== undefined) _q.set("
                        + TypeScriptFileWriter.stringLiteral(wire) + ", String(input." + memberName + "))");
                }
            }
            for (String memberName : b.queryParamsMembers.keySet()) {
                writer.line("      for (const [k, v] of Object.entries(input." + memberName
                    + " ?? {})) { if (!_q.has(k)) _q.set(k, String(v)) }");
            }
            writer.line("      const _qs = _q.toString()");
            urlExpr = "`${_base}" + pathTemplate + "${_qs ? '?' + _qs : ''}`";
        } else {
            urlExpr = "`${_base}" + pathTemplate + "`";
        }

        // Request init.
        StringBuilder init = new StringBuilder("{ method: '" + method + "', headers");
        if (hasBody) {
            init.append(", body: ").append(bodyExpr(b));
        }
        init.append(" }");

        writer.line("      const res = await _fetch(" + urlExpr + ", " + init + ")");
        writer.line("      if (!res.ok) _throwError(res.status, await _readBody(res))");
        if (hasOutput) {
            String output = OperationTypes.outputType(index, op);
            writer.line("      return (await res.json()) as " + output);
        }
        writer.line("    },");
    }

    /** The TS path template with each {@code @httpLabel} substituted (URI-encoded). */
    private String buildPathTemplate(String uri, InputBindings b) {
        // Drop any literal query suffix in the @http uri (rare; bindings drive the query).
        int q = uri.indexOf('?');
        String path = q >= 0 ? uri.substring(0, q) : uri;
        if (b != null) {
            for (String labelName : b.pathMembers.keySet()) {
                String sub = "${encodeURIComponent(String(input." + labelName + "))}";
                // Greedy ({name+}) and ordinary ({name}) label tokens.
                path = path.replace("{" + labelName + "+}", sub).replace("{" + labelName + "}", sub);
            }
        }
        return path;
    }

    /** The JSON body expression: the @httpPayload member, or an implicit-body object. */
    private String bodyExpr(InputBindings b) {
        if (b.hasPayload()) {
            return "JSON.stringify(input." + b.payloadMemberName + ")";
        }
        List<String> fields = new ArrayList<>();
        for (String memberName : b.bodyMembers.keySet()) {
            fields.add(memberName + ": input." + memberName);
        }
        return "JSON.stringify({ " + String.join(", ", fields) + " })";
    }
}
