package com.smithyhono.writers;

import com.smithyhono.ModelIndex;
import com.smithyhono.traits.McpPromptsTrait;
import software.amazon.smithy.build.FileManifest;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.traits.HttpTrait;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/**
 * Emits {@code mcp.gen.ts} — the MCP tool manifest (Plan 14).
 *
 * <p>One {@code MCP_TOOLS} entry per HTTP operation: the registry {@code OperationMeta}
 * (which already carries name / method / path / description / CRUD annotations) plus the
 * operation's input and output Zod schemas. The runtime bridge
 * ({@code @smithy-hono/mcp-core}) turns each entry into an MCP tool — deriving the tool
 * input/output JSON Schema from the SAME Zod schemas the router validates, so the tool
 * contract can't drift from the wire contract.
 *
 * <p>Schemas are imported straight from the per-group gen files (and {@code shared.gen}
 * for shapes shared across groups), never via {@code index.ts}, to avoid an import cycle
 * (index re-exports this file).
 */
public class McpManifestEmitter {

    private final ModelIndex index;
    private final Set<ShapeId> sharedShapeIds;

    public McpManifestEmitter(ModelIndex index, Set<ShapeId> sharedShapeIds) {
        this.index = index;
        this.sharedShapeIds = sharedShapeIds;
    }

    private static String kebab(String name) {
        return name.replaceAll("([A-Z])", "-$1").toLowerCase().replaceFirst("^-", "");
    }

    /** A valid namespace-import identifier for a group (e.g. "Task" -> "_task"). */
    private static String aliasFor(String groupName) {
        return "_" + kebab(groupName).replace("-", "_");
    }

    /**
     * Emits mcp.gen.ts in registry order. Returns true if written (≥1 HTTP op).
     *
     * @param groups operations keyed by resource group (insertion-ordered) — gives the
     *               gen file each op's schemas live in.
     */
    public boolean emit(Map<String, List<OperationShape>> groups,
                        software.amazon.smithy.build.FileManifest manifest) {
        // op id -> group name (every HTTP op belongs to exactly one group).
        Map<ShapeId, String> groupOf = new LinkedHashMap<>();
        for (Map.Entry<String, List<OperationShape>> e : groups.entrySet()) {
            for (OperationShape op : e.getValue()) groupOf.put(op.getId(), e.getKey());
        }

        List<OperationShape> httpOps = index.getOperations().stream()
            .filter(op -> op.hasTrait(HttpTrait.class))
            .toList();
        if (httpOps.isEmpty()) return false;

        // Resolve each op's input/output schema reference, tracking which imports we need.
        Set<String> usedGroupAliases = new LinkedHashSet<>();
        boolean[] usesShared = {false};
        boolean[] needsZod = {false};

        StringBuilder tools = new StringBuilder();
        for (OperationShape op : httpOps) {
            String groupName = groupOf.get(op.getId());
            if (groupName == null) continue; // not in a router group (shouldn't happen for HTTP ops)

            String inputRef = schemaRef(index.getInput(op), groupName, usedGroupAliases, usesShared);
            if (inputRef == null) { inputRef = "z.object({}).strict()"; needsZod[0] = true; }
            String outputRef = schemaRef(index.getOutput(op), groupName, usedGroupAliases, usesShared);

            tools.append("  { op: OPERATIONS.").append(op.getId().getName())
                .append(", inputSchema: ").append(inputRef);
            if (outputRef != null) tools.append(", outputSchema: ").append(outputRef);
            tools.append(" },\n");
        }

        TypeScriptFileWriter writer = new TypeScriptFileWriter();
        writer.comment("DO NOT EDIT — regenerated by smithy-hono on every build");
        writer.blank();
        writer.comment("MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to");
        writer.comment("createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.");
        writer.blank();
        writer.line("import { OPERATIONS } from './registry.gen'");
        if (needsZod[0]) writer.line("import { z } from 'zod'");
        for (Map.Entry<String, List<OperationShape>> e : groups.entrySet()) {
            String groupName = e.getKey();
            if (!usedGroupAliases.contains(groupName)) continue;
            writer.line("import * as " + aliasFor(groupName) + " from './" + kebab(groupName) + ".gen'");
        }
        if (usesShared[0]) writer.line("import * as _shared from './shared.gen'");
        writer.blank();

        writer.line("export const MCP_TOOLS = [");
        // tools already ends with a newline per entry; append trimmed of the trailing one.
        for (String l : tools.toString().split("\n")) writer.line(l);
        writer.line("]");
        writer.blank();

        // MCP_PROMPTS (Plan 14, §12). ALWAYS emitted — even as `[]` — so the runtime
        // import (`createMcpHandler({ prompts: MCP_PROMPTS, … })`) is stable across
        // services regardless of whether any prompt was authored.
        emitPrompts(writer, httpOps);

        writer.write(manifest, "mcp.gen.ts");
        return true;
    }

    /**
     * Emits the {@code MCP_PROMPTS} array (§12.4): service-level prompts first (names
     * required, no derivation), then operation-anchored prompts in registry order. Each
     * op-anchored prompt is resolved per §12.2 — name defaults to {@code kebab(op.name)},
     * the description gains a {@code (uses the <Op> tool)} reference, and an omitted
     * {@code arguments} is derived from the op's input members.
     */
    private void emitPrompts(TypeScriptFileWriter writer, List<OperationShape> httpOps) {
        List<String> entries = new ArrayList<>();

        // Service-level: exactly what's declared (name required; no derivation).
        for (McpPromptsTrait.Prompt p : index.servicePrompts()) {
            entries.add(renderPrompt(
                p.getName().orElse(""),
                p.getDescription().orElse(null),
                explicitArgs(p),
                p.getTemplate()));
        }

        // Operation-anchored: default name, tool-referenced description, derived args.
        for (OperationShape op : httpOps) {
            String opName = op.getId().getName();
            for (McpPromptsTrait.Prompt p : index.promptsFor(op)) {
                String name = p.getName().filter(n -> !n.isEmpty()).orElse(kebab(opName));

                String description = p.getDescription().orElse(null);
                String toolRef = "(uses the " + opName + " tool)";
                description = description == null || description.isEmpty()
                    ? toolRef
                    : description + " " + toolRef;

                List<String> args = p.isArgumentsDeclared()
                    ? explicitArgs(p)
                    : derivedArgs(op);

                entries.add(renderPrompt(name, description, args, p.getTemplate()));
            }
        }

        if (entries.isEmpty()) {
            writer.line("export const MCP_PROMPTS = [] as const");
        } else {
            writer.line("export const MCP_PROMPTS = [");
            for (String entry : entries) writer.line(entry);
            writer.line("] as const");
        }
        writer.blank();
    }

    /** Renders the explicitly-declared arguments of a prompt as TS object literals. */
    private List<String> explicitArgs(McpPromptsTrait.Prompt p) {
        List<String> args = new ArrayList<>();
        for (McpPromptsTrait.Argument a : p.getArguments()) {
            args.add(argLiteral(a.getName(), a.getDescription().orElse(null), a.isRequired()));
        }
        return args;
    }

    /** Renders the arguments derived from an op's input members (§12.2) as TS literals. */
    private List<String> derivedArgs(OperationShape op) {
        List<String> args = new ArrayList<>();
        for (ModelIndex.DerivedPromptArgument a : index.derivePromptArguments(op)) {
            args.add(argLiteral(a.name, a.description, a.required));
        }
        return args;
    }

    private String argLiteral(String name, String description, boolean required) {
        StringBuilder sb = new StringBuilder("{ name: ")
            .append(TypeScriptFileWriter.stringLiteral(name));
        if (description != null) {
            sb.append(", description: ").append(TypeScriptFileWriter.stringLiteral(description));
        }
        sb.append(", required: ").append(required).append(" }");
        return sb.toString();
    }

    /** Renders one fully-resolved MCP_PROMPTS entry. */
    private String renderPrompt(String name, String description, List<String> args, String template) {
        StringBuilder sb = new StringBuilder("  { name: ")
            .append(TypeScriptFileWriter.stringLiteral(name));
        if (description != null) {
            sb.append(", description: ").append(TypeScriptFileWriter.stringLiteral(description));
        }
        sb.append(", arguments: [");
        sb.append(String.join(", ", args));
        sb.append("]");
        sb.append(", template: ").append(TypeScriptFileWriter.stringLiteral(template));
        sb.append(" },");
        return sb.toString();
    }

    /**
     * A reference to a structure's emitted Zod schema var (e.g. {@code _task.CreateTaskInputSchema}),
     * or null when the operation has no input/output structure (Unit). Records the alias /
     * shared usage so the caller can emit the matching import.
     */
    private String schemaRef(Optional<StructureShape> struct, String groupName,
                            Set<String> usedGroupAliases, boolean[] usesShared) {
        if (struct.isEmpty()) return null;
        StructureShape s = struct.get();
        String schemaVar = ZodEmitter.schemaVarName(s.getId().getName());
        if (sharedShapeIds.contains(s.getId())) {
            usesShared[0] = true;
            return "_shared." + schemaVar;
        }
        usedGroupAliases.add(groupName);
        return aliasFor(groupName) + "." + schemaVar;
    }
}
