package com.smithyhono.writers;

import com.smithyhono.ModelIndex;
import com.smithyhono.ModelIndex.CrudVerb;
import com.smithyhono.traits.LiveTrait;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ResourceShape;
import software.amazon.smithy.model.traits.HttpTrait;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Emits {@code registry.gen.ts} — the operation metadata registry (ARCH-06).
 *
 * <p>The generated registry is the keystone the runtime security layer consumes:
 * middleware looks up an operation by name or by method+path and applies policy
 * without re-parsing protocol details.
 */
public class MetadataRegistryEmitter {

    private final ModelIndex index;
    private final int fallbackMaxPageSize;
    private final int fallbackDefaultPageSize;

    /** Uses the conventional RATE-06 fallback caps (100 / 25) when a model omits them. */
    public MetadataRegistryEmitter(ModelIndex index) {
        this(index, 100, 25);
    }

    public MetadataRegistryEmitter(ModelIndex index, int fallbackMaxPageSize, int fallbackDefaultPageSize) {
        this.index = index;
        this.fallbackMaxPageSize = fallbackMaxPageSize;
        this.fallbackDefaultPageSize = fallbackDefaultPageSize;
    }

    /**
     * Emits registry.gen.ts for every HTTP operation in the service. Returns true
     * if the file was written (i.e. there is at least one HTTP operation).
     */
    public boolean emit(List<OperationShape> operations, software.amazon.smithy.build.FileManifest manifest) {
        List<OperationShape> httpOps = operations.stream()
            .filter(op -> op.hasTrait(HttpTrait.class))
            .collect(Collectors.toList());
        if (httpOps.isEmpty()) return false;

        TypeScriptFileWriter writer = new TypeScriptFileWriter();
        writer.comment("DO NOT EDIT — regenerated by smithy-hono on every build");
        writer.blank();

        emitTypes(writer);

        writer.comment("---- Operations ----");
        writer.blank();
        writer.line("export const OPERATIONS: Record<string, OperationMeta> = {");
        for (OperationShape op : httpOps) {
            emitOperation(op, writer);
        }
        // Phase L1: synthetic entries for each @live resource's SSE subscribe endpoint. The
        // endpoint isn't a modeled operation, so the security pipeline needs a registry entry to
        // (a) authenticate the subscribe exactly like the read op and (b) apply the streaming
        // route class so the security-headers middleware skips `Cache-Control: no-store`.
        for (ResourceShape resource : index.liveResources()) {
            emitLiveOperation(resource, writer);
        }
        writer.line("}");
        writer.blank();

        writer.comment("---- Route index (method + path -> meta) ----");
        writer.blank();
        writer.line("export const OPERATION_BY_ROUTE: Record<string, OperationMeta> = {");
        for (OperationShape op : httpOps) {
            HttpTrait http = op.expectTrait(HttpTrait.class);
            String method = http.getMethod().toUpperCase();
            String path = index.smithyUriToHono(http.getUri().toString());
            String opName = op.getId().getName();
            writer.line("  '" + method + " " + path + "': OPERATIONS." + opName + ",");
        }
        for (ResourceShape resource : index.liveResources()) {
            String path = LiveEmitter.liveRoutePath(resource, index.liveConfig(resource), index);
            writer.line("  'GET " + path + "': OPERATIONS." + LiveEmitter.liveOpName(resource) + ",");
        }
        writer.line("}");
        writer.blank();

        writer.write(manifest, "registry.gen.ts");
        return true;
    }

    private void emitTypes(TypeScriptFileWriter writer) {
        writer.line("export interface OperationMeta {");
        writer.line("  name: string");
        // Plan 14: @documentation surfaced for MCP tool descriptions (and human docs).
        // Optional + emitted only when the model carries @documentation, so undocumented
        // ops keep their existing registry shape.
        writer.line("  description?: string");
        writer.line("  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'");
        writer.line("  path: string");
        writer.line("  authSchemes: AuthScheme[]");
        writer.line("  readonly: boolean");
        writer.line("  streaming?: boolean");
        // Phase L1: marks a @live SSE subscribe endpoint. Implies streaming (the security-headers
        // middleware skips `Cache-Control: no-store`). Emitted ONLY when the service has @live
        // resources, so a non-@live service's registry.gen.ts stays byte-identical (no churn).
        if (!index.liveResources().isEmpty()) {
            writer.line("  live?: boolean");
        }
        writer.line("  requiredPermissions: string[]");
        writer.line("  pagination?: { maxPageSize: number; defaultPageSize: number }");
        writer.line("  cost: number");
        writer.line("  constraints: { maxBodyBytes?: number; hasConstrainedInput: boolean }");
        writer.line("  sensitiveFields?: string[]");
        // Plan 13 (P3): CRUD lifecycle metadata for @persisted-resource ops. Optional and
        // absent for every other op (additive, no churn for non-persisted services).
        writer.line("  resource?: string");
        writer.line("  crudVerb?: 'create' | 'put' | 'read' | 'update' | 'delete' | 'list'");
        writer.line("  identifierMembers?: string[]");
        writer.line("}");
        writer.blank();
        writer.line("export type AuthScheme =");
        writer.line("  | { type: 'oidc' }");
        writer.line("  | { type: 'sigv4Hmac' }");
        writer.line("  | { type: 'anonymous' }");
        writer.blank();
    }

    private void emitOperation(OperationShape op, TypeScriptFileWriter writer) {
        HttpTrait http = op.expectTrait(HttpTrait.class);
        String opName = op.getId().getName();
        String method = http.getMethod().toUpperCase();
        String path = index.smithyUriToHono(http.getUri().toString());

        writer.line("  " + opName + ": {");
        writer.line("    name: '" + opName + "',");
        index.documentationFor(op).ifPresent(doc ->
            writer.line("    description: " + TypeScriptFileWriter.stringLiteral(doc) + ","));
        writer.line("    method: '" + method + "',");
        writer.line("    path: '" + path + "',");
        writer.line("    authSchemes: [" + renderAuthSchemes(op) + "],");
        writer.line("    readonly: " + index.isReadonly(op) + ",");
        if (index.isStreaming(op)) {
            writer.line("    streaming: true,");
        }
        writer.line("    requiredPermissions: [" + renderPermissions(op) + "],");

        Optional<ModelIndex.Pagination> pagination =
            index.paginationFor(op, fallbackMaxPageSize, fallbackDefaultPageSize);
        pagination.ifPresent(p -> writer.line("    pagination: { maxPageSize: " + p.maxPageSize
            + ", defaultPageSize: " + p.defaultPageSize + " },"));

        writer.line("    cost: " + index.costFor(op) + ",");
        writer.line("    constraints: { hasConstrainedInput: " + index.hasConstrainedInput(op) + " },");

        // RT-13 — machine-readable @sensitive field paths for the runtime redaction
        // seam. Emitted only when present, so non-sensitive ops don't churn.
        List<String> sensitive = index.sensitiveFieldPaths(op);
        if (!sensitive.isEmpty()) {
            String paths = sensitive.stream().map(p -> "'" + p + "'").collect(Collectors.joining(", "));
            writer.line("    sensitiveFields: [" + paths + "],");
        }

        // Plan 13 (P3): CRUD lifecycle metadata, emitted only for @persisted-resource
        // lifecycle ops so non-persisted ops keep their existing registry shape.
        index.crudMetaFor(op).ifPresent(meta -> {
            writer.line("    resource: '" + meta.resource + "',");
            writer.line("    crudVerb: '" + meta.verb.name().toLowerCase() + "',");
            String ids = meta.identifierMembers.stream()
                .map(m -> "'" + m + "'").collect(Collectors.joining(", "));
            writer.line("    identifierMembers: [" + ids + "],");
        });

        writer.line("  },");
    }

    /**
     * Emits the synthetic {@code OperationMeta} for a {@code @live} resource's SSE subscribe
     * endpoint ({@code GET /<resource>/:id/events}). Its auth schemes + required permissions
     * mirror the resource's READ op so the pipeline authenticates a subscribe exactly like a
     * read (Phase L2); {@code streaming} + {@code live} mark it as an SSE stream route class.
     */
    private void emitLiveOperation(ResourceShape resource, TypeScriptFileWriter writer) {
        LiveTrait cfg = index.liveConfig(resource);
        String opName = LiveEmitter.liveOpName(resource);
        String path = LiveEmitter.liveRoutePath(resource, cfg, index);
        Optional<OperationShape> read =
            Optional.ofNullable(index.lifecycleOps(resource).get(CrudVerb.READ));

        writer.line("  " + opName + ": {");
        writer.line("    name: '" + opName + "',");
        writer.line("    method: 'GET',");
        writer.line("    path: '" + path + "',");
        String authSchemes = read.map(this::renderAuthSchemes).orElse("");
        writer.line("    authSchemes: [" + authSchemes + "],");
        writer.line("    readonly: true,");
        writer.line("    streaming: true,");
        writer.line("    live: true,");
        String perms = read.map(this::renderPermissions).orElse("");
        writer.line("    requiredPermissions: [" + perms + "],");
        writer.line("    cost: 1,");
        writer.line("    constraints: { hasConstrainedInput: false },");
        writer.line("    resource: '" + resource.getId().getName() + "',");
        writer.line("  },");
    }

    private String renderAuthSchemes(OperationShape op) {
        List<String> schemes = index.authSchemesFor(op);
        List<String> rendered = new ArrayList<>();
        for (String type : schemes) {
            rendered.add("{ type: '" + type + "' }");
        }
        return String.join(", ", rendered);
    }

    private String renderPermissions(OperationShape op) {
        return index.requiredPermissionFor(op)
            .map(TypeScriptFileWriter::stringLiteral)
            .orElse("");
    }
}
