package com.smithyhono.writers;

import com.smithyhono.traits.RequiresAuthTrait;
import software.amazon.smithy.build.FileManifest;
import software.amazon.smithy.model.shapes.OperationShape;

import java.util.*;

public class PermissionsEmitter {

    public static String toConstantName(String permission) {
        return permission.replaceAll("[^a-zA-Z0-9]+", "_")
                         .replaceAll("^_+|_+$", "")
                         .toUpperCase();
    }

    /** Emits permissions.gen.ts and returns true, or returns false if no permissions exist. */
    public boolean emit(Collection<List<OperationShape>> allGroups, FileManifest manifest) {
        Set<String> permissions = collectPermissions(allGroups);
        if (permissions.isEmpty()) return false;

        TypeScriptFileWriter writer = new TypeScriptFileWriter();
        writer.comment("DO NOT EDIT — regenerated by smithy-hono on every build");
        writer.blank();
        writer.line("export const Permissions = {");
        for (String permission : permissions) {
            writer.line("  " + toConstantName(permission) + ": " + TypeScriptFileWriter.stringLiteral(permission) + ",");
        }
        writer.line("} as const");
        writer.blank();
        writer.line("export type Permission = typeof Permissions[keyof typeof Permissions]");
        writer.blank();

        writer.write(manifest, "permissions.gen.ts");
        return true;
    }

    private Set<String> collectPermissions(Collection<List<OperationShape>> allGroups) {
        Set<String> permissions = new LinkedHashSet<>();
        for (List<OperationShape> ops : allGroups) {
            for (OperationShape op : ops) {
                if (op.hasTrait(RequiresAuthTrait.class)) {
                    op.expectTrait(RequiresAuthTrait.class).getPermission()
                        .filter(p -> !p.isEmpty())
                        .ifPresent(permissions::add);
                }
            }
        }
        return permissions;
    }
}
