package com.smithyhono.writers;

import com.smithyhono.traits.SseEventTrait;
import software.amazon.smithy.build.FileManifest;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.*;

import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates events.gen.ts for all structures annotated with @sseEvent.
 *
 * Output contains:
 *   - Zod schema + TypeScript type per event structure
 *   - Discriminated union (e.g. DeadeuceEvent)
 *   - Emitter interface (e.g. DeadeuceEventEmitter)
 *   - Typed EventSource client class (e.g. DeadeuceEventSource)
 *
 * Also emits events.template.ts — a one-time Hono SSE endpoint template the
 * user copies to src/routes/ and customises; never regenerated by the plugin.
 */
public class SseEmitter {

    private final Model model;
    private final ServiceShape service;

    public SseEmitter(Model model, ServiceShape service) {
        this.model = model;
        this.service = service;
    }

    /** Returns true if any @sseEvent shapes exist in the model. */
    public boolean hasEvents() {
        return model.getStructureShapes().stream()
            .anyMatch(s -> s.hasTrait(SseEventTrait.class));
    }

    /** Returns true if any SSE events were found and emitted. */
    public boolean emit(FileManifest manifest) {
        List<StructureShape> events = model.getStructureShapes().stream()
            .filter(s -> s.hasTrait(SseEventTrait.class))
            .sorted(Comparator.comparing(s -> s.getId().getName()))
            .collect(Collectors.toList());

        if (events.isEmpty()) return false;

        String prefix = derivePrefix();

        emitEventsFile(manifest, events, prefix);
        emitTemplateFile(manifest, events, prefix);
        return true;
    }

    // ── events.gen.ts ──────────────────────────────────────────────────────────

    private void emitEventsFile(FileManifest manifest, List<StructureShape> events, String prefix) {
        TypeScriptFileWriter w = new TypeScriptFileWriter();

        w.comment("DO NOT EDIT — regenerated by smithy-hono on every build");
        w.blank();
        w.line("import { z } from 'zod'");
        w.blank();

        w.comment("---- SSE Event Schemas ----");
        w.blank();

        SchemaDeclarationEmitter schemaEmitter = new SchemaDeclarationEmitter(model);
        schemaEmitter.emitDeclarations(events, w);

        w.comment("---- SSE Event Union ----");
        w.blank();

        emitDiscriminatedUnion(w, events, prefix);
        w.blank();

        w.comment("---- Event Emitter Interface ----");
        w.blank();

        emitEmitterInterface(w, events, prefix);
        w.blank();

        w.comment("---- Event Source Client ----");
        w.blank();

        emitEventSourceClass(w, events, prefix);

        w.write(manifest, "events.gen.ts");
    }

    private void emitDiscriminatedUnion(TypeScriptFileWriter w, List<StructureShape> events, String prefix) {
        w.line("export type " + prefix + "Event =");
        for (int i = 0; i < events.size(); i++) {
            StructureShape event = events.get(i);
            String eventType = event.expectTrait(SseEventTrait.class).getEventType();
            String typeName = ZodEmitter.safeTypeName(event.getId().getName());
            String suffix = (i < events.size() - 1) ? "" : "";
            w.line("  | { type: " + TypeScriptFileWriter.stringLiteral(eventType) + "; data: " + typeName + " }" + suffix);
        }
    }

    private void emitEmitterInterface(TypeScriptFileWriter w, List<StructureShape> events, String prefix) {
        w.line("export interface " + prefix + "EventEmitter {");
        w.line("  emit(channelId: string, event: " + prefix + "Event): Promise<void>");
        w.line("}");
    }

    private void emitEventSourceClass(TypeScriptFileWriter w, List<StructureShape> events, String prefix) {
        String unionType = prefix + "Event";
        String className = prefix + "EventSource";

        w.line("export class " + className + " {");
        w.line("  private readonly es: EventSource");
        w.line("  private readonly handlers = new Map<string, Set<(data: unknown) => void>>()");
        w.blank();
        w.line("  constructor(endpoint: string, channelId: string) {");
        w.line("    this.es = new EventSource(`${endpoint}?channelId=${encodeURIComponent(channelId)}`)");
        w.line("    this.es.onmessage = (e) => {");
        w.line("      try {");
        w.line("        const { type, data } = JSON.parse(e.data) as " + unionType);
        w.line("        this.handlers.get(type)?.forEach(h => h(data))");
        w.line("      } catch {}");
        w.line("    }");

        // Named event listeners (SSE event: field)
        StringBuilder allTypes = new StringBuilder("    const allTypes: " + unionType + "['type'][] = [");
        List<String> typeStrings = events.stream()
            .map(e -> TypeScriptFileWriter.stringLiteral(e.expectTrait(SseEventTrait.class).getEventType()))
            .collect(Collectors.toList());
        allTypes.append(String.join(", ", typeStrings));
        allTypes.append("]");
        w.line(allTypes.toString());

        w.line("    for (const t of allTypes) {");
        w.line("      this.es.addEventListener(t, (e) => {");
        w.line("        try {");
        w.line("          const data = JSON.parse((e as MessageEvent).data)");
        w.line("          this.handlers.get(t)?.forEach(h => h(data))");
        w.line("        } catch {}");
        w.line("      })");
        w.line("    }");
        w.line("  }");
        w.blank();
        w.line("  on<T extends " + unionType + "['type']>(");
        w.line("    type: T,");
        w.line("    handler: (data: Extract<" + unionType + ", { type: T }>['data']) => void");
        w.line("  ): () => void {");
        w.line("    if (!this.handlers.has(type)) this.handlers.set(type, new Set())");
        w.line("    this.handlers.get(type)!.add(handler as (data: unknown) => void)");
        w.line("    return () => this.handlers.get(type)?.delete(handler as (data: unknown) => void)");
        w.line("  }");
        w.blank();
        w.line("  close(): void { this.es.close() }");
        w.line("}");
    }

    // ── events.template.ts ─────────────────────────────────────────────────────

    private void emitTemplateFile(FileManifest manifest, List<StructureShape> events, String prefix) {
        TypeScriptFileWriter w = new TypeScriptFileWriter();
        String unionType = prefix + "Event";
        String emitterType = prefix + "EventEmitter";

        w.comment("TEMPLATE — copy to src/routes/events.ts and customise");
        w.comment("This file is a reference; it is NOT the live generated output.");
        w.blank();
        w.line("import { streamSSE } from 'hono/streaming'");
        w.line("import { Hono } from 'hono'");
        w.line("import type { " + emitterType + ", " + unionType + " } from '../generated/events.gen'");
        w.blank();
        w.comment("Extend the emitter interface with a subscribe method for your bus implementation.");
        w.line("type EventBusWithSubscribe = " + emitterType + " & {");
        w.line("  subscribe(channelId: string, handler: (event: " + unionType + ") => Promise<void>): () => void");
        w.line("}");
        w.blank();
        w.line("export function createEventsRouter(eventBus: EventBusWithSubscribe): Hono {");
        w.line("  const app = new Hono()");
        w.blank();
        w.line("  app.get('/:channelId/events', async (c) => {");
        w.line("    const { channelId } = c.req.param()");
        w.line("    return streamSSE(c, async (stream) => {");
        w.line("      const unsubscribe = eventBus.subscribe(channelId, async (event: " + unionType + ") => {");
        w.line("        await stream.writeSSE({");
        w.line("          event: event.type,");
        w.line("          data: JSON.stringify(event.data),");
        w.line("          id: String(Date.now()),");
        w.line("        })");
        w.line("      })");
        w.line("      stream.onAbort(() => unsubscribe())");
        w.line("    })");
        w.line("  })");
        w.blank();
        w.line("  return app");
        w.line("}");

        w.write(manifest, "events.template.ts");
    }

    // ── helpers ────────────────────────────────────────────────────────────────

    private String derivePrefix() {
        return service.getId().getName().replace("Service", "").replace("service", "");
    }
}
