// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import * as _shape_coverage from './shape-coverage.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.PutShapes, inputSchema: _shape_coverage.PutShapesInputSchema, outputSchema: _shape_coverage.PutShapesOutputSchema },
]

export const MCP_PROMPTS = [] as const

