// DO NOT EDIT — regenerated by smithy-hono on every build

import { Hono } from 'hono'
import type { Context, MiddlewareHandler } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'
import type { SecurityEnv } from '@smithy-hono/security-core'

// ---- Schemas ----

export const ShapesBodySchema = z.object({
  epochTs: z.number().optional(),
  isoTs: z.string().datetime().optional(),
  tags: z.array(z.string()).refine((a) => new Set(a.map((x) => JSON.stringify(x))).size === a.length, { message: 'items must be unique' }).optional(),
  bignum: z.string().regex(/^-?\d+$/).optional(),
  amount: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
  data: z.string().regex(/^[A-Za-z0-9+/]*={0,2}$/).optional(),
  byStatus: z.record(z.enum(["active", "inactive"]), z.number().int()).optional(),
  items: z.array(z.string()).default([]),
  label: z.string().default("a\"quoted\" value"),
  /** @sensitive — excluded from debug logs */
  secret: z.string().optional(),
}).strict()
export type ShapesBody = z.infer<typeof ShapesBodySchema>

export const PutShapesInputSchema = z.object({
  body: ShapesBodySchema,
}).strict()
export type PutShapesInput = z.infer<typeof PutShapesInputSchema>

export const PutShapesOutputSchema = z.object({
  ok: z.boolean(),
}).strict()
export type PutShapesOutput = z.infer<typeof PutShapesOutputSchema>

// ---- Operations interface ----

export interface ShapeCoverageOperations {
  PutShapes(input: { body: ShapesBody }, c?: Context<SecurityEnv>): Promise<PutShapesOutput>
}

// ---- Middleware interface ----

export interface ShapeCoverageMiddleware {
  all?: MiddlewareHandler[]
  PutShapes?: MiddlewareHandler[]
}

// ---- Router factory ----

function _chain(mws: MiddlewareHandler[]): MiddlewareHandler {
  return async (c, next) => {
    let i = 0
    const run = async (): Promise<void> => { i < mws.length ? await mws[i++](c, run) : await next() }
    await run()
  }
}

export function createShapeCoverageRouter(ops: ShapeCoverageOperations, middleware?: ShapeCoverageMiddleware): Hono {
  const app = new Hono()

  // @http(method: "POST", uri: "/shapes")
  app.post('/shapes',
    _chain([...(middleware?.all ?? []), ...(middleware?.PutShapes ?? [])]),
    zValidator('json', ShapesBodySchema, (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = { body: c.req.valid('json') }
      try {
        const result = await ops.PutShapes(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  return app
}
