// DO NOT EDIT — regenerated by smithy-hono on every build

import type { ReservedBody, PutReservedOutput } from './reserved.gen'
import type { FetchLike } from './client-runtime.gen'
import { SmithyError } from './errors'

// ---- Client options ----

export interface ReservedClientOptions {
  /** Defaults to globalThis.fetch. In tests pass app.request.bind(app). */
  fetch?: FetchLike
  /** Prepended to every request path (e.g. 'https://api.example.com'). Defaults to ''. */
  baseUrl?: string
  /** Headers merged into every request — cookies / CSRF / signing. Awaited per request. */
  headers?: () => HeadersInit | Promise<HeadersInit>
}

// ---- Client interface ----

export interface ReservedClient {
  PutReserved(input: { body: ReservedBody }): Promise<PutReservedOutput>
}

// ---- Internal helpers ----

async function _readBody(res: Response): Promise<unknown> {
  const text = await res.text()
  return text ? JSON.parse(text) : undefined
}

function _throwError(status: number, body: unknown): never {
  const b = (body ?? {}) as { code?: string; message?: string; fieldErrors?: unknown }
  const message = b.message
    ?? (b.fieldErrors !== undefined ? 'ValidationException: ' + JSON.stringify(b.fieldErrors) : 'HTTP ' + status)
  throw new SmithyError(message, status, status >= 500 ? 'server' : 'client')
}

// ---- Client factory ----

export function createReservedClient(opts: ReservedClientOptions = {}): ReservedClient {
  const _fetch: FetchLike = opts.fetch ?? globalThis.fetch
  const _base = opts.baseUrl ?? ''
  const _headers = opts.headers ?? (() => ({}))
  return {
    async PutReserved(input) {
      const headers = new Headers(await _headers())
      headers.set('content-type', 'application/json')
      const res = await _fetch(`${_base}/reserved`, { method: 'POST', headers, body: JSON.stringify(input.body) })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as PutReservedOutput
    },
  }
}
