// DO NOT EDIT — regenerated by smithy-hono on every build

import { Hono } from 'hono'
import type { Context, MiddlewareHandler } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'
import type { SecurityEnv } from '@smithy-hono/security-core'

// ---- Schemas ----

export const NumberShapeSchema = z.object({
  amount: z.number().int(),
}).strict()
export type NumberShape = z.infer<typeof NumberShapeSchema>

export const ReservedBodySchema = z.object({
  "class": z.string(),
  "default": z.string().optional(),
  num: NumberShapeSchema.optional(),
}).strict()
export type ReservedBody = z.infer<typeof ReservedBodySchema>

export const PutReservedInputSchema = z.object({
  body: ReservedBodySchema,
}).strict()
export type PutReservedInput = z.infer<typeof PutReservedInputSchema>

export const PutReservedOutputSchema = z.object({
  ok: z.boolean(),
}).strict()
export type PutReservedOutput = z.infer<typeof PutReservedOutputSchema>

// ---- Operations interface ----

export interface ReservedOperations {
  PutReserved(input: { body: ReservedBody }, c?: Context<SecurityEnv>): Promise<PutReservedOutput>
}

// ---- Middleware interface ----

export interface ReservedMiddleware {
  all?: MiddlewareHandler[]
  PutReserved?: MiddlewareHandler[]
}

// ---- Router factory ----

function _chain(mws: MiddlewareHandler[]): MiddlewareHandler {
  return async (c, next) => {
    let i = 0
    const run = async (): Promise<void> => { i < mws.length ? await mws[i++](c, run) : await next() }
    await run()
  }
}

export function createReservedRouter(ops: ReservedOperations, middleware?: ReservedMiddleware): Hono {
  const app = new Hono()

  // @http(method: "POST", uri: "/reserved")
  app.post('/reserved',
    _chain([...(middleware?.all ?? []), ...(middleware?.PutReserved ?? [])]),
    zValidator('json', ReservedBodySchema, (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = { body: c.req.valid('json') }
      try {
        const result = await ops.PutReserved(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  return app
}
