/**
 * Render the Kubernetes manifests for a {@link NodeDeployConfig} + the resolved
 * deploy context (domain, api prefix, namespace, built image tags). Pure — no I/O,
 * fully unit-tested — the CLI feeds the returned YAML straight to `kubectl apply`.
 *
 * The shape mirrors the repo's hand-written deploy assets (`deploy/node/k8s/*`,
 * `deploy/node-web/k8s/*`):
 *   - the API `Deployment` + `Service` (ClusterIP :3000) with the restricted
 *     Pod-Security-Standard security context (runAsNonRoot / runAsUser 1000 /
 *     drop ALL / RuntimeDefault seccomp) and `envFrom` the per-app Secret;
 *   - when `config.web` is set, an nginx web `Deployment` + `Service` + `Ingress`
 *     (TLS host = domain, cert-manager annotation) and a `ConfigMap` holding a
 *     generic same-origin nginx config that serves the SPA and reverse-proxies
 *     `apiPrefix/*` to the API Service.
 *
 * Secrets are NEVER rendered here — the Secret object is created out-of-band by
 * the CLI (`kubectl create secret …`), and the API Deployment binds it by
 * reference via `envFrom`.
 */
import type { NodeDeployConfig } from './config.js'

/** The resolved deploy context the CLI computes before rendering. */
export interface ManifestContext {
  /** Public hostname (used for the Ingress host + TLS). */
  domain: string
  /** API path prefix reverse-proxied to the API Service (and the probe paths). */
  apiPrefix: string
  /** Kubernetes namespace every object is placed in. */
  namespace: string
  /** Fully-qualified API container image (repo:tag, registry-prefixed if configured). */
  image: string
  /** Fully-qualified web (nginx) container image. Required when `config.web` is set. */
  webImage?: string
}

const GENERATED_BANNER = '# Generated by @smithy-hono/deploy-node — DO NOT EDIT BY HAND.'

/** Names of the k8s objects derived from `appName` (single source of truth). */
export function objectNames(appName: string): {
  api: string
  web: string
  secret: string
  nginxConfig: string
  tlsSecret: string
} {
  return {
    api: appName,
    web: `${appName}-web`,
    secret: `${appName}-secrets`,
    nginxConfig: `${appName}-web-nginx`,
    tlsSecret: `${appName}-web-tls`,
  }
}

/** Indent every non-empty line of `text` by `spaces` (for YAML block scalars). */
function indentLines(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces)
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n')
}

/** Render the API container's `env:` list entries (10-space `env:` → 12-space items). */
function renderEnvEntries(env: Record<string, string>): string {
  return Object.entries(env)
    .map(([k, v]) => `            - name: ${k}\n              value: ${JSON.stringify(String(v))}`)
    .join('\n')
}

/**
 * The generic same-origin nginx config, adapted from
 * `deploy/node-web/default.conf.template` to a SINGLE `apiPrefix/` proxy location
 * plus an SPA `try_files` fallback. Preserves:
 *   - the runtime `resolver` gotcha (`${NGINX_LOCAL_RESOLVERS}` populated by the
 *     nginx image entrypoint from the pod's /etc/resolv.conf, so the API upstream
 *     name is resolved per-request and nginx boots even if the API isn't up yet);
 *   - the X-Forwarded-Proto trust maps (honor a forwarded `https` ONLY from the
 *     trusted ingress peer, else fall back to this hop's `$scheme`) so a spoofed
 *     inbound header from an untrusted peer can never defeat the API's `assertHttps`;
 *   - the SPA-shell security response headers.
 *
 * `apiUpstream` is the in-cluster API Service DNS name (`<appName>:3000`).
 */
export function renderNginxConfig(apiUpstream: string, apiPrefix: string): string {
  // Kept as a plain string so the template literal below does NOT try to
  // interpolate it — the nginx image entrypoint substitutes it at container start.
  const localResolvers = '${NGINX_LOCAL_RESOLVERS}'
  return String.raw`# Generated by @smithy-hono/deploy-node — same-origin SPA front door.
# Mounted as an nginx template (/etc/nginx/templates/default.conf.template); the
# image entrypoint (NGINX_ENTRYPOINT_LOCAL_RESOLVERS=1) runs envsubst so only
# ${localResolvers} is substituted (from the pod's /etc/resolv.conf — the cluster
# DNS). Every $nginx runtime variable below is left untouched.

# Trust an inbound X-Forwarded-Proto ONLY when the immediate peer is the ingress
# tier (RFC1918 / pod-service CIDRs); otherwise fall back to this hop's $scheme.
map $remote_addr $trusted_proto_peer {
  default              0;
  "~^10\."             1;
  "~^192\.168\."       1;
  "~^172\.(1[6-9]|2[0-9]|3[0-1])\."  1;
  "127.0.0.1"          1;
}

# Normalize the inbound value to a known scheme (guards a spoofed trusted peer).
map $http_x_forwarded_proto $inbound_proto {
  default   "";
  "https"   "https";
  "http"    "http";
}

# Effective forwarded proto: the trusted-peer inbound value if present, else the
# real transport scheme of this hop.
map "$trusted_proto_peer:$inbound_proto" $fwd_proto {
  default        $scheme;
  "1:https"      "https";
  "1:http"       "http";
}

server {
  listen       8080;
  server_name  _;
  root         /usr/share/nginx/html;
  index        index.html;

  # Resolve the API name at REQUEST time (not boot time) so this container starts
  # even if the API Service isn't up yet (502s per-request until it is).
  resolver ${localResolvers} valid=30s ipv6=off;
  set $api_upstream ${apiUpstream};

  gzip            on;
  gzip_types      text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;

  # Security headers for the nginx-served SPA shell (the API stamps its own).
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header X-Frame-Options           "DENY"             always;
  add_header Content-Security-Policy    "frame-ancestors 'none'" always;
  add_header X-Content-Type-Options    "nosniff"          always;
  add_header Referrer-Policy           "no-referrer"      always;

  # ---- API surface -> proxied same-origin to the Node API Service ------------
  # proxy_pass ...$request_uri preserves the full original path+query (required
  # when proxy_pass uses a variable). $fwd_proto / $remote_addr set the forwarded
  # scheme + client IP the API security pipeline reads.
  location ${apiPrefix}/ {
    proxy_pass http://$api_upstream$request_uri;
    proxy_http_version 1.1;
    proxy_set_header   Host              $host;
    proxy_set_header   X-Real-IP         $remote_addr;
    proxy_set_header   X-Forwarded-For   $remote_addr;
    proxy_set_header   X-Forwarded-Proto $fwd_proto;
    proxy_set_header   X-Forwarded-Host  $host;
    proxy_buffering off;
    proxy_read_timeout 300s;
  }

  # ---- SPA -------------------------------------------------------------------
  # Everything else is the single-page app: serve the file if it exists, else fall
  # back to index.html so client-side routes resolve.
  location / {
    try_files $uri $uri/ /index.html;
  }
}
`
}

/**
 * Render the web (nginx) image Dockerfile. Kept pure (a string) so the CLI can
 * write it to disk and `docker build` it. The image is just nginx + the built SPA;
 * the same-origin nginx config is supplied at runtime from the ConfigMap (mounted
 * at /etc/nginx/templates), so the image itself is app-agnostic.
 */
export function renderWebDockerfile(webDir: string): string {
  return `# Generated by @smithy-hono/deploy-node — nginx same-origin front door.
FROM nginx:1.27-alpine
# Opt into the image's resolver autodetection so its entrypoint populates
# \${NGINX_LOCAL_RESOLVERS} from /etc/resolv.conf before envsubst runs the
# ConfigMap-mounted template.
ENV NGINX_ENTRYPOINT_LOCAL_RESOLVERS=1
COPY ${webDir} /usr/share/nginx/html
# Make nginx's cache/run dirs writable by an arbitrary non-root uid, and drop the
# \`user\` directive (the master runs as 1000, can't setuid the workers anyway).
RUN chgrp -R 0 /var/cache/nginx /var/run /var/log/nginx \\
 && chmod -R g+rwX /var/cache/nginx /var/run /var/log/nginx \\
 && sed -i '/^user /d' /etc/nginx/nginx.conf
EXPOSE 8080
`
}

/** Render the API Deployment + Service (ClusterIP :3000). */
function renderApi(config: NodeDeployConfig, ctx: ManifestContext, names: ReturnType<typeof objectNames>): string {
  const env: Record<string, string> = { PORT: '3000' }
  // A web front-door means a trusted nginx proxy sits in front — honor its
  // X-Forwarded-* so the API's assertHttps / client-IP keys are correct.
  if (config.web) env.TRUST_PROXY_HEADERS = '1'
  Object.assign(env, config.env?.({ domain: ctx.domain, apiPrefix: ctx.apiPrefix }) ?? {})

  const hasSecrets = (config.secrets?.length ?? 0) > 0
  const envFrom = hasSecrets
    ? `          envFrom:
            - secretRef:
                name: ${names.secret}
`
    : ''

  const deployment = `${GENERATED_BANNER}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${names.api}
  namespace: ${ctx.namespace}
  labels:
    app: ${names.api}
    app.kubernetes.io/part-of: ${config.appName}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${names.api}
  template:
    metadata:
      labels:
        app: ${names.api}
    spec:
      # Restricted Pod Security Standard: runAsUser must be NUMERIC so the kubelet
      # can verify non-root even with the image's non-numeric \`USER node\`.
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: ${ctx.image}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 3000
          env:
${renderEnvEntries(env)}
${envFrom}          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: ${ctx.apiPrefix}/healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: ${ctx.apiPrefix}/readyz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5`

  const service = `apiVersion: v1
kind: Service
metadata:
  name: ${names.api}
  namespace: ${ctx.namespace}
  labels:
    app.kubernetes.io/part-of: ${config.appName}
spec:
  type: ClusterIP
  selector:
    app: ${names.api}
  ports:
    - port: 3000
      targetPort: 3000`

  return `${deployment}\n---\n${service}`
}

/** Render the web ConfigMap + Deployment + Service + Ingress (only when config.web). */
function renderWeb(config: NodeDeployConfig, ctx: ManifestContext, names: ReturnType<typeof objectNames>): string {
  if (!ctx.webImage) {
    throw new Error('renderManifests: config.web is set but ctx.webImage is missing — build the web image first.')
  }
  const nginx = renderNginxConfig(`${names.api}:3000`, ctx.apiPrefix)

  const configMap = `apiVersion: v1
kind: ConfigMap
metadata:
  name: ${names.nginxConfig}
  namespace: ${ctx.namespace}
  labels:
    app.kubernetes.io/part-of: ${config.appName}
data:
  default.conf.template: |
${indentLines(nginx, 4)}`

  const deployment = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${names.web}
  namespace: ${ctx.namespace}
  labels:
    app: ${names.web}
    app.kubernetes.io/part-of: ${config.appName}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${names.web}
  template:
    metadata:
      labels:
        app: ${names.web}
    spec:
      # nginx listens on 8080 (unprivileged), cache/run dirs group-writable, so it
      # runs as an arbitrary non-root uid with no privilege escalation.
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: ${ctx.webImage}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/templates
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: nginx-config
          configMap:
            name: ${names.nginxConfig}`

  const service = `apiVersion: v1
kind: Service
metadata:
  name: ${names.web}
  namespace: ${ctx.namespace}
  labels:
    app.kubernetes.io/part-of: ${config.appName}
spec:
  type: ClusterIP
  selector:
    app: ${names.web}
  ports:
    - port: 80
      targetPort: 8080`

  // The public edge. TLS terminates HERE (required: __Host- cookies need https)
  // and the Ingress speaks plaintext http to the web Service; nginx forwards the
  // X-Forwarded-Proto to the API for its assertHttps check.
  const ingress = `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${names.web}
  namespace: ${ctx.namespace}
  labels:
    app.kubernetes.io/part-of: ${config.appName}
  annotations:
    # Adjust to your ingress controller / cert-manager issuer.
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - ${ctx.domain}
      secretName: ${names.tlsSecret}
  rules:
    - host: ${ctx.domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${names.web}
                port:
                  number: 80`

  return [configMap, deployment, service, ingress].join('\n---\n')
}

/**
 * Render the full manifest bundle (concatenated YAML documents separated by
 * `---`). Always renders the API Deployment + Service; appends the web
 * ConfigMap/Deployment/Service/Ingress when `config.web` is set.
 */
export function renderManifests(config: NodeDeployConfig, ctx: ManifestContext): string {
  const names = objectNames(config.appName)
  const docs = [renderApi(config, ctx, names)]
  if (config.web) docs.push(renderWeb(config, ctx, names))
  return docs.join('\n---\n') + '\n'
}
