import { describe, it, expect } from 'vitest'
import { renderManifests, renderNginxConfig, renderWebDockerfile, objectNames } from './manifests.js'
import type { ManifestContext } from './manifests.js'
import type { NodeDeployConfig } from './config.js'

/** Split a rendered bundle into its individual YAML documents. */
function docs(yaml: string): string[] {
  return yaml.split('\n---\n')
}

/** A representative full-stack config: web front-door + derived env + secrets. */
function fullConfig(): NodeDeployConfig {
  return {
    appName: 'demo',
    web: { dir: 'web/dist', apiPrefix: '/api', buildCommand: 'npm run build' },
    env: ({ domain, apiPrefix }) => ({
      DATABASE_URL: 'postgres://db:5432/app',
      REDIS_URL: 'redis://redis:6379',
      OIDC_REDIRECT_URI: `https://${domain}${apiPrefix}/auth/callback`,
    }),
    secrets: [{ name: 'SIGNING_KEY', generate: 'hmac-hex' }],
  }
}

const ctxFull: ManifestContext = {
  domain: 'app.example.com',
  apiPrefix: '/api',
  namespace: 'production',
  image: 'registry.example.com/me/demo:v1',
  webImage: 'registry.example.com/me/demo-web:v1',
}

describe('renderManifests — full stack (API + web)', () => {
  const out = renderManifests(fullConfig(), ctxFull)

  it('renders every expected kind', () => {
    expect(out).toContain('kind: Deployment')
    expect(out).toContain('kind: Service')
    expect(out).toContain('kind: Ingress')
    expect(out).toContain('kind: ConfigMap')
    // Two Deployments (API + web) and two Services.
    expect(out.match(/kind: Deployment/g)).toHaveLength(2)
    expect(out.match(/kind: Service/g)).toHaveLength(2)
  })

  it('places the API container on port 3000 with the built image', () => {
    expect(out).toContain('containerPort: 3000')
    expect(out).toContain('image: registry.example.com/me/demo:v1')
  })

  it('applies the restricted Pod Security Standard security context', () => {
    expect(out).toContain('runAsNonRoot: true')
    expect(out).toContain('runAsUser: 1000')
    expect(out).toContain('drop: ["ALL"]')
    expect(out).toContain('type: RuntimeDefault')
    expect(out).toContain('allowPrivilegeEscalation: false')
  })

  it('probes liveness /api/healthz and readiness /api/readyz on the api prefix', () => {
    expect(out).toContain('path: /api/healthz')
    expect(out).toContain('path: /api/readyz')
  })

  it('carries the base env (PORT, TRUST_PROXY_HEADERS) plus the derived DB/redis env', () => {
    expect(out).toContain('name: PORT')
    expect(out).toContain('value: "3000"')
    expect(out).toContain('name: TRUST_PROXY_HEADERS')
    expect(out).toContain('name: DATABASE_URL')
    expect(out).toContain('value: "postgres://db:5432/app"')
    expect(out).toContain('name: REDIS_URL')
    expect(out).toContain('value: "redis://redis:6379"')
    // Derived from the domain + apiPrefix.
    expect(out).toContain('value: "https://app.example.com/api/auth/callback"')
  })

  it('binds the per-app Secret via envFrom', () => {
    expect(out).toContain('envFrom:')
    expect(out).toContain('name: demo-secrets')
  })

  it('places every object in the requested namespace', () => {
    expect(out.match(/namespace: production/g)?.length).toBeGreaterThanOrEqual(5)
  })

  it('renders the Ingress with the domain host + cert-manager TLS', () => {
    expect(out).toContain('host: app.example.com')
    expect(out).toContain('- app.example.com')
    expect(out).toContain('secretName: demo-web-tls')
    expect(out).toContain('cert-manager.io/cluster-issuer: "letsencrypt-prod"')
  })

  it('renders the nginx ConfigMap with the apiPrefix proxy location + resolver gotcha', () => {
    expect(out).toContain('name: demo-web-nginx')
    expect(out).toContain('default.conf.template: |')
    expect(out).toContain('location /api/ {')
    expect(out).toContain('proxy_pass http://$api_upstream$request_uri;')
    expect(out).toContain('set $api_upstream demo:3000;')
    expect(out).toContain('${NGINX_LOCAL_RESOLVERS}')
  })

  it('mounts the ConfigMap into the web pod as an nginx template', () => {
    expect(out).toContain('mountPath: /etc/nginx/templates')
    expect(out).toContain('configMap:')
    expect(out).toContain('image: registry.example.com/me/demo-web:v1')
    expect(out).toContain('containerPort: 8080')
  })

  it('is valid-looking multi-doc YAML (leads with the generated banner)', () => {
    expect(out.startsWith('# Generated by @smithy-hono/deploy-node')).toBe(true)
    expect(docs(out).length).toBe(6) // api Deploy+Svc, web ConfigMap+Deploy+Svc+Ingress
  })
})

describe('renderManifests — API-only (no web)', () => {
  const config: NodeDeployConfig = {
    appName: 'api',
    env: () => ({ REDIS_URL: 'redis://redis:6379' }),
    secrets: [{ name: 'SIGNING_KEY', generate: 'hmac-hex' }],
  }
  const ctx: ManifestContext = {
    domain: 'api.example.com',
    apiPrefix: '/api',
    namespace: 'default',
    image: 'api:latest',
  }
  const out = renderManifests(config, ctx)

  it('renders only the API Deployment + Service (no Ingress / ConfigMap / web)', () => {
    expect(out).toContain('kind: Deployment')
    expect(out).toContain('kind: Service')
    expect(out).not.toContain('kind: Ingress')
    expect(out).not.toContain('kind: ConfigMap')
    expect(out).not.toContain('-web')
    expect(docs(out).length).toBe(2)
  })

  it('does NOT set TRUST_PROXY_HEADERS without a web front-door', () => {
    expect(out).not.toContain('TRUST_PROXY_HEADERS')
  })

  it('still binds the Secret via envFrom', () => {
    expect(out).toContain('name: api-secrets')
  })
})

describe('renderManifests — no secrets', () => {
  it('omits envFrom when the config declares no secrets', () => {
    const out = renderManifests({ appName: 'demo' }, {
      domain: 'app.example.com',
      apiPrefix: '/api',
      namespace: 'default',
      image: 'demo:latest',
    })
    expect(out).not.toContain('envFrom')
    expect(out).not.toContain('secretRef')
  })
})

describe('renderManifests — guards', () => {
  it('throws when web is configured but webImage is missing from ctx', () => {
    expect(() =>
      renderManifests(
        { appName: 'demo', web: { dir: 'web/dist' } },
        { domain: 'app.example.com', apiPrefix: '/api', namespace: 'default', image: 'demo:latest' },
      ),
    ).toThrow(/webImage is missing/)
  })
})

describe('renderNginxConfig', () => {
  const cfg = renderNginxConfig('demo:3000', '/gateway')

  it('proxies the configured apiPrefix and preserves the X-Forwarded-Proto trust maps', () => {
    expect(cfg).toContain('location /gateway/ {')
    expect(cfg).toContain('map $remote_addr $trusted_proto_peer')
    expect(cfg).toContain('map "$trusted_proto_peer:$inbound_proto" $fwd_proto')
    expect(cfg).toContain('proxy_set_header   X-Forwarded-Proto $fwd_proto;')
    expect(cfg).toContain('proxy_set_header   X-Forwarded-For   $remote_addr;')
  })

  it('sets the runtime resolver + per-request upstream + SPA fallback', () => {
    expect(cfg).toContain('resolver ${NGINX_LOCAL_RESOLVERS} valid=30s ipv6=off;')
    expect(cfg).toContain('set $api_upstream demo:3000;')
    expect(cfg).toContain('try_files $uri $uri/ /index.html;')
  })

  it('stamps the SPA-shell security headers', () => {
    expect(cfg).toContain('add_header Strict-Transport-Security')
    expect(cfg).toContain('add_header X-Frame-Options           "DENY"')
    expect(cfg).toContain('add_header Content-Security-Policy    "frame-ancestors \'none\'"')
  })
})

describe('renderWebDockerfile', () => {
  it('builds an nginx image copying the SPA dir + enabling local resolvers', () => {
    const df = renderWebDockerfile('web/dist')
    expect(df).toContain('FROM nginx:1.27-alpine')
    expect(df).toContain('ENV NGINX_ENTRYPOINT_LOCAL_RESOLVERS=1')
    expect(df).toContain('COPY web/dist /usr/share/nginx/html')
    expect(df).toContain('EXPOSE 8080')
  })
})

describe('objectNames', () => {
  it('derives every object name from appName', () => {
    expect(objectNames('demo')).toEqual({
      api: 'demo',
      web: 'demo-web',
      secret: 'demo-secrets',
      nginxConfig: 'demo-web-nginx',
      tlsSecret: 'demo-web-tls',
    })
  })
})
