// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import * as _note from './note.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.CreateNote, inputSchema: _note.CreateNoteInputSchema, outputSchema: _note.CreateNoteOutputSchema },
  { op: OPERATIONS.ListNotes, inputSchema: _note.ListNotesInputSchema, outputSchema: _note.ListNotesOutputSchema },
]

export const MCP_PROMPTS = [
  { name: "summarize-notes", description: "Summarize the current notes.", arguments: [{ name: "tone", description: "Desired tone", required: false }], template: "List the notes (call the list-notes tool) and summarize them. Tone: {tone}." },
  { name: "create-note", description: "Draft a note from free text. (uses the CreateNote tool)", arguments: [{ name: "body", description: "The note text.", required: true }], template: "Create a note from: {body}. Keep it concise." },
] as const

