// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import * as _mixed_bindings from './mixed-bindings.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.CreateItem, inputSchema: _mixed_bindings.CreateItemInputSchema, outputSchema: _mixed_bindings.CreateItemOutputSchema },
  { op: OPERATIONS.GetItem, inputSchema: _mixed_bindings.GetItemInputSchema, outputSchema: _mixed_bindings.GetItemOutputSchema },
  { op: OPERATIONS.SearchItems, inputSchema: _mixed_bindings.SearchItemsInputSchema, outputSchema: _mixed_bindings.SearchItemsOutputSchema },
  { op: OPERATIONS.UpdateItem, inputSchema: _mixed_bindings.UpdateItemInputSchema, outputSchema: _mixed_bindings.UpdateItemOutputSchema },
]

export const MCP_PROMPTS = [] as const

