// DO NOT EDIT — regenerated by smithy-hono on every build

import { Hono } from 'hono'
import type { Context, MiddlewareHandler } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'
import { authorize } from '@smithy-hono/security-core'
import { OPERATIONS } from './registry.gen'
import type { SecurityEnv, SecurityVariables } from '@smithy-hono/security-core'

// ---- Schemas ----

export const CreateItemBodySchema = z.object({
  name: z.string(),
  description: z.string().optional(),
}).strict()
export type CreateItemBody = z.infer<typeof CreateItemBodySchema>

export const CreateItemInputSchema = z.object({
  body: CreateItemBodySchema,
  idempotencyKey: z.string().optional(),
}).strict()
export type CreateItemInput = z.infer<typeof CreateItemInputSchema>

export const ItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional(),
}).strict()
export type Item = z.infer<typeof ItemSchema>

export const CreateItemOutputSchema = z.object({
  item: ItemSchema,
}).strict()
export type CreateItemOutput = z.infer<typeof CreateItemOutputSchema>

export const GetItemInputSchema = z.object({
  id: z.string(),
  requestId: z.string().optional(),
}).strict()
export type GetItemInput = z.infer<typeof GetItemInputSchema>

export const GetItemOutputSchema = z.object({
  item: ItemSchema,
}).strict()
export type GetItemOutput = z.infer<typeof GetItemOutputSchema>

export const SearchItemsInputSchema = z.object({
  q: z.string().optional(),
  limit: z.number().int().optional(),
  page: z.number().int().optional(),
  extraParams: z.record(z.string(), z.string()).optional(),
  meta: z.record(z.string(), z.string()).optional(),
}).strict()
export type SearchItemsInput = z.infer<typeof SearchItemsInputSchema>

export const SearchItemsOutputSchema = z.object({
  items: z.array(ItemSchema),
  total: z.number().int().optional(),
}).strict()
export type SearchItemsOutput = z.infer<typeof SearchItemsOutputSchema>

export const UpdateItemInputSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  description: z.string().optional(),
}).strict()
export type UpdateItemInput = z.infer<typeof UpdateItemInputSchema>

export const UpdateItemOutputSchema = z.object({
  item: ItemSchema,
}).strict()
export type UpdateItemOutput = z.infer<typeof UpdateItemOutputSchema>

// ---- Operations interface ----

export interface MixedBindingsOperations {
  CreateItem(input: { body: CreateItemBody; idempotencyKey?: string }, c?: Context<SecurityEnv>): Promise<CreateItemOutput>
  GetItem(input: { id: string; requestId?: string }, c?: Context<SecurityEnv>): Promise<GetItemOutput>
  SearchItems(input: { q?: string; limit?: number; page?: number; extraParams?: Record<string, string>; meta?: Record<string, string> }, c?: Context<SecurityEnv>): Promise<SearchItemsOutput>
  UpdateItem(input: { id: string; name?: string; description?: string }, c?: Context<SecurityEnv>): Promise<UpdateItemOutput>
}

// ---- Env type ----

export type MixedBindingsEnv = { Variables: SecurityVariables }

// ---- Middleware interface ----

export interface MixedBindingsMiddleware {
  all?: MiddlewareHandler[]
  CreateItem?: MiddlewareHandler[]
  GetItem?: MiddlewareHandler[]
  SearchItems?: MiddlewareHandler[]
  UpdateItem?: MiddlewareHandler[]
}

// ---- Router factory ----

function _chain(mws: MiddlewareHandler[]): MiddlewareHandler {
  return async (c, next) => {
    let i = 0
    const run = async (): Promise<void> => { i < mws.length ? await mws[i++](c, run) : await next() }
    await run()
  }
}

export function createMixedBindingsRouter(ops: MixedBindingsOperations, middleware?: MixedBindingsMiddleware): Hono {
  const app = new Hono()

  // @http(method: "POST", uri: "/items")
  // @requiresAuth(permission: "items.write")
  app.post('/items',
    _chain([...(middleware?.all ?? []), ...(middleware?.CreateItem ?? [])]),
    zValidator('header', z.object({
      'x-idempotency-key': z.string().optional(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    zValidator('json', CreateItemBodySchema, (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    authorize(OPERATIONS.CreateItem),
    async (c) => {
      const input = {
        idempotencyKey: c.req.valid('header')['x-idempotency-key'],
        body: c.req.valid('json')
      }
      try {
        const result = await ops.CreateItem(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 201)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  // @http(method: "GET", uri: "/items/{id}")
  app.get('/items/:id',
    _chain([...(middleware?.all ?? []), ...(middleware?.GetItem ?? [])]),
    zValidator('param', z.object({
      id: z.string(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    zValidator('header', z.object({
      'x-request-id': z.string().optional(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = {
        ...c.req.valid('param'),
        requestId: c.req.valid('header')['x-request-id']
      }
      try {
        const result = await ops.GetItem(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  // @http(method: "GET", uri: "/items")
  app.get('/items',
    _chain([...(middleware?.all ?? []), ...(middleware?.SearchItems ?? [])]),
    zValidator('query', z.object({
      q: z.string().optional(),
      limit: z.string().regex(/^-?\d+$/).transform(Number).pipe(z.number().int()).optional(),
      page: z.string().regex(/^-?\d+$/).transform(Number).pipe(z.number().int()).optional(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = {
        ...c.req.valid('query'),
        extraParams: Object.fromEntries(Object.entries(c.req.query()).filter(([k]) => !['q', 'limit', 'page'].includes(k))),
        meta: Object.fromEntries(Object.entries(c.req.header()).filter(([k]) => k.startsWith('x-meta-')).map(([k, v]) => [k.slice(7), v]))
      }
      try {
        const result = await ops.SearchItems(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  // @http(method: "PUT", uri: "/items/{id}")
  app.put('/items/:id',
    _chain([...(middleware?.all ?? []), ...(middleware?.UpdateItem ?? [])]),
    zValidator('param', z.object({
      id: z.string(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    zValidator('json', z.object({
      name: z.string().optional(),
      description: z.string().optional(),
    }).strict(), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    authorize(OPERATIONS.UpdateItem),
    async (c) => {
      const input = {
        ...c.req.valid('param'),
        ...c.req.valid('json')
      }
      try {
        const result = await ops.UpdateItem(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  return app
}
