// DO NOT EDIT — regenerated by smithy-hono on every build

import type { CreateItemBody, CreateItemOutput, GetItemOutput, SearchItemsOutput, UpdateItemOutput } from './mixed-bindings.gen'
import type { FetchLike } from './client-runtime.gen'
import { SmithyError } from './errors'

// ---- Client options ----

export interface MixedBindingsClientOptions {
  /** Defaults to globalThis.fetch. In tests pass app.request.bind(app). */
  fetch?: FetchLike
  /** Prepended to every request path (e.g. 'https://api.example.com'). Defaults to ''. */
  baseUrl?: string
  /** Headers merged into every request — cookies / CSRF / signing. Awaited per request. */
  headers?: () => HeadersInit | Promise<HeadersInit>
}

// ---- Client interface ----

export interface MixedBindingsClient {
  CreateItem(input: { body: CreateItemBody; idempotencyKey?: string }): Promise<CreateItemOutput>
  GetItem(input: { id: string; requestId?: string }): Promise<GetItemOutput>
  SearchItems(input: { q?: string; limit?: number; page?: number; extraParams?: Record<string, string>; meta?: Record<string, string> }): Promise<SearchItemsOutput>
  UpdateItem(input: { id: string; name?: string; description?: string }): Promise<UpdateItemOutput>
}

// ---- Internal helpers ----

async function _readBody(res: Response): Promise<unknown> {
  const text = await res.text()
  return text ? JSON.parse(text) : undefined
}

function _throwError(status: number, body: unknown): never {
  const b = (body ?? {}) as { code?: string; message?: string; fieldErrors?: unknown }
  const message = b.message
    ?? (b.fieldErrors !== undefined ? 'ValidationException: ' + JSON.stringify(b.fieldErrors) : 'HTTP ' + status)
  throw new SmithyError(message, status, status >= 500 ? 'server' : 'client')
}

// ---- Client factory ----

export function createMixedBindingsClient(opts: MixedBindingsClientOptions = {}): MixedBindingsClient {
  const _fetch: FetchLike = opts.fetch ?? globalThis.fetch
  const _base = opts.baseUrl ?? ''
  const _headers = opts.headers ?? (() => ({}))
  return {
    async CreateItem(input) {
      const headers = new Headers(await _headers())
      if (input.idempotencyKey !== undefined) headers.set("X-Idempotency-Key", String(input.idempotencyKey))
      headers.set('content-type', 'application/json')
      const res = await _fetch(`${_base}/items`, { method: 'POST', headers, body: JSON.stringify(input.body) })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as CreateItemOutput
    },
    async GetItem(input) {
      const headers = new Headers(await _headers())
      if (input.requestId !== undefined) headers.set("X-Request-Id", String(input.requestId))
      const res = await _fetch(`${_base}/items/${encodeURIComponent(String(input.id))}`, { method: 'GET', headers })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as GetItemOutput
    },
    async SearchItems(input) {
      const headers = new Headers(await _headers())
      for (const [k, v] of Object.entries(input.meta ?? {})) headers.set("x-meta-" + k, String(v))
      const _q = new URLSearchParams()
      if (input.q !== undefined) _q.set("q", String(input.q))
      if (input.limit !== undefined) _q.set("limit", String(input.limit))
      if (input.page !== undefined) _q.set("page", String(input.page))
      for (const [k, v] of Object.entries(input.extraParams ?? {})) { if (!_q.has(k)) _q.set(k, String(v)) }
      const _qs = _q.toString()
      const res = await _fetch(`${_base}/items${_qs ? '?' + _qs : ''}`, { method: 'GET', headers })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as SearchItemsOutput
    },
    async UpdateItem(input) {
      const headers = new Headers(await _headers())
      headers.set('content-type', 'application/json')
      const res = await _fetch(`${_base}/items/${encodeURIComponent(String(input.id))}`, { method: 'PUT', headers, body: JSON.stringify({ name: input.name, description: input.description }) })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as UpdateItemOutput
    },
  }
}
