// DO NOT EDIT — regenerated by smithy-hono on every build

import { Hono } from 'hono'
import type { Context, MiddlewareHandler } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'
import type { SecurityEnv } from '@smithy-hono/security-core'

// ---- Schemas ----

export const CreateResourceInputSchema = z.object({
  name: z.string(),
}).strict()
export type CreateResourceInput = z.infer<typeof CreateResourceInputSchema>

export const CreateResourceOutputSchema = z.object({
  id: z.string(),
  name: z.string(),
}).strict()
export type CreateResourceOutput = z.infer<typeof CreateResourceOutputSchema>

export const GetResourceInputSchema = z.object({
  id: z.string(),
}).strict()
export type GetResourceInput = z.infer<typeof GetResourceInputSchema>

export const GetResourceOutputSchema = z.object({
  id: z.string(),
  name: z.string(),
}).strict()
export type GetResourceOutput = z.infer<typeof GetResourceOutputSchema>

// ---- Errors ----

export class ServiceUnavailableError extends Error {
  readonly $statusCode = 503
  readonly $fault = 'server' as const
  constructor(message: string) {
    super(message)
    this.name = 'ServiceUnavailableError'
    Object.setPrototypeOf(this, ServiceUnavailableError.prototype)
  }
}

export class ValidationError extends Error {
  readonly $statusCode = 400
  readonly $fault = 'client' as const
  constructor(message: string) {
    super(message)
    this.name = 'ValidationError'
    Object.setPrototypeOf(this, ValidationError.prototype)
  }
}

export class ThrottlingException extends Error {
  readonly $statusCode = 429
  readonly $fault = 'client' as const
  readonly $retryable = true as const
  readonly $throttling = true as const
  constructor(message: string) {
    super(message)
    this.name = 'ThrottlingException'
    Object.setPrototypeOf(this, ThrottlingException.prototype)
  }
}

export class ConflictError extends Error {
  readonly $statusCode = 409
  readonly $fault = 'client' as const
  constructor(message: string) {
    super(message)
    this.name = 'ConflictError'
    Object.setPrototypeOf(this, ConflictError.prototype)
  }
}

export class NotFoundError extends Error {
  readonly $statusCode = 404
  readonly $fault = 'client' as const
  constructor(message: string) {
    super(message)
    this.name = 'NotFoundError'
    Object.setPrototypeOf(this, NotFoundError.prototype)
  }
}

export class ForbiddenError extends Error {
  readonly $statusCode = 403
  readonly $fault = 'client' as const
  constructor(message: string) {
    super(message)
    this.name = 'ForbiddenError'
    Object.setPrototypeOf(this, ForbiddenError.prototype)
  }
}

// ---- Operations interface ----

export interface ErrorShapeOperations {
  CreateResource(input: { name: string }, c?: Context<SecurityEnv>): Promise<CreateResourceOutput>
  GetResource(input: { id: string }, c?: Context<SecurityEnv>): Promise<GetResourceOutput>
}

// ---- Middleware interface ----

export interface ErrorShapeMiddleware {
  all?: MiddlewareHandler[]
  CreateResource?: MiddlewareHandler[]
  GetResource?: MiddlewareHandler[]
}

// ---- Router factory ----

function _chain(mws: MiddlewareHandler[]): MiddlewareHandler {
  return async (c, next) => {
    let i = 0
    const run = async (): Promise<void> => { i < mws.length ? await mws[i++](c, run) : await next() }
    await run()
  }
}

export function createErrorShapeRouter(ops: ErrorShapeOperations, middleware?: ErrorShapeMiddleware): Hono {
  const app = new Hono()

  // @http(method: "POST", uri: "/resources")
  app.post('/resources',
    _chain([...(middleware?.all ?? []), ...(middleware?.CreateResource ?? [])]),
    zValidator('json', z.object({
      name: z.string(),
    }).strict(), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = { ...c.req.valid('json') }
      try {
        const result = await ops.CreateResource(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 201)
      } catch (e) {
        if (e instanceof ServiceUnavailableError)
          return c.json({ code: 'ServiceUnavailableError', message: e.message }, e.$statusCode)
        if (e instanceof ValidationError)
          return c.json({ code: 'ValidationError', message: e.message }, e.$statusCode)
        if (e instanceof ThrottlingException)
          return c.json({ code: 'ThrottlingException', message: e.message }, e.$statusCode)
        if (e instanceof ConflictError)
          return c.json({ code: 'ConflictError', message: e.message }, e.$statusCode)
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  // @http(method: "GET", uri: "/resources/{id}")
  app.get('/resources/:id',
    _chain([...(middleware?.all ?? []), ...(middleware?.GetResource ?? [])]),
    zValidator('param', z.object({
      id: z.string(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = { ...c.req.valid('param') }
      try {
        const result = await ops.GetResource(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        if (e instanceof ServiceUnavailableError)
          return c.json({ code: 'ServiceUnavailableError', message: e.message }, e.$statusCode)
        if (e instanceof ValidationError)
          return c.json({ code: 'ValidationError', message: e.message }, e.$statusCode)
        if (e instanceof ThrottlingException)
          return c.json({ code: 'ThrottlingException', message: e.message }, e.$statusCode)
        if (e instanceof NotFoundError)
          return c.json({ code: 'NotFoundError', message: e.message }, e.$statusCode)
        if (e instanceof ForbiddenError)
          return c.json({ code: 'ForbiddenError', message: e.message }, e.$statusCode)
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  return app
}
