// DO NOT EDIT — regenerated by smithy-hono on every build

import type { CreateResourceOutput, GetResourceOutput } from './error-shape.gen'
import { ServiceUnavailableError, ValidationError, ThrottlingException, ConflictError, NotFoundError, ForbiddenError } from './error-shape.gen'
import type { FetchLike } from './client-runtime.gen'
import { SmithyError } from './errors'

// ---- Client options ----

export interface ErrorShapeClientOptions {
  /** Defaults to globalThis.fetch. In tests pass app.request.bind(app). */
  fetch?: FetchLike
  /** Prepended to every request path (e.g. 'https://api.example.com'). Defaults to ''. */
  baseUrl?: string
  /** Headers merged into every request — cookies / CSRF / signing. Awaited per request. */
  headers?: () => HeadersInit | Promise<HeadersInit>
}

// ---- Client interface ----

export interface ErrorShapeClient {
  CreateResource(input: { name: string }): Promise<CreateResourceOutput>
  GetResource(input: { id: string }): Promise<GetResourceOutput>
}

// ---- Internal helpers ----

async function _readBody(res: Response): Promise<unknown> {
  const text = await res.text()
  return text ? JSON.parse(text) : undefined
}

function _throwError(status: number, body: unknown): never {
  const b = (body ?? {}) as { code?: string; message?: string; fieldErrors?: unknown }
  const message = b.message
    ?? (b.fieldErrors !== undefined ? 'ValidationException: ' + JSON.stringify(b.fieldErrors) : 'HTTP ' + status)
  switch (b.code) {
    case 'ServiceUnavailableError': throw new ServiceUnavailableError(message)
    case 'ValidationError': throw new ValidationError(message)
    case 'ThrottlingException': throw new ThrottlingException(message)
    case 'ConflictError': throw new ConflictError(message)
    case 'NotFoundError': throw new NotFoundError(message)
    case 'ForbiddenError': throw new ForbiddenError(message)
  }
  throw new SmithyError(message, status, status >= 500 ? 'server' : 'client')
}

// ---- Client factory ----

export function createErrorShapeClient(opts: ErrorShapeClientOptions = {}): ErrorShapeClient {
  const _fetch: FetchLike = opts.fetch ?? globalThis.fetch
  const _base = opts.baseUrl ?? ''
  const _headers = opts.headers ?? (() => ({}))
  return {
    async CreateResource(input) {
      const headers = new Headers(await _headers())
      headers.set('content-type', 'application/json')
      const res = await _fetch(`${_base}/resources`, { method: 'POST', headers, body: JSON.stringify({ name: input.name }) })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as CreateResourceOutput
    },
    async GetResource(input) {
      const headers = new Headers(await _headers())
      const res = await _fetch(`${_base}/resources/${encodeURIComponent(String(input.id))}`, { method: 'GET', headers })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as GetResourceOutput
    },
  }
}
