// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import * as _error_shape from './error-shape.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.CreateResource, inputSchema: _error_shape.CreateResourceInputSchema, outputSchema: _error_shape.CreateResourceOutputSchema },
  { op: OPERATIONS.GetResource, inputSchema: _error_shape.GetResourceInputSchema, outputSchema: _error_shape.GetResourceOutputSchema },
]

export const MCP_PROMPTS = [] as const

