-- D1 schema for the CRUD demo's Task store.
--
-- Generated by `@smithy-hono/adapter-cf`'s d1CreateTableSql('tasks') — the
-- canonical DataStore schema (scope + id primary key, JSON value blob, version
-- column for optimistic-concurrency CAS, deleted_at for soft-delete tombstones).
-- Keep this in sync with d1CreateTableSql if the adapter schema changes.
--
-- Apply: `wrangler d1 migrations apply crud-tasks [--local]` (see wrangler.toml).

CREATE TABLE IF NOT EXISTS "tasks" (
  scope TEXT NOT NULL,
  id TEXT NOT NULL,
  value TEXT NOT NULL,
  version INTEGER NOT NULL,
  deleted_at TEXT,
  PRIMARY KEY (scope, id)
);
