// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import * as _output_binding from './output-binding.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.MakeWidget, inputSchema: _output_binding.MakeWidgetInputSchema, outputSchema: _output_binding.MakeWidgetOutputSchema },
]

export const MCP_PROMPTS = [] as const

