// DO NOT EDIT — regenerated by smithy-hono on every build

import { Hono } from 'hono'
import type { Context, MiddlewareHandler } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'
import type { ContentfulStatusCode } from 'hono/utils/http-status'
import type { SecurityEnv } from '@smithy-hono/security-core'

// ---- Schemas ----

export const WidgetBodySchema = z.object({
  name: z.string(),
}).strict()
export type WidgetBody = z.infer<typeof WidgetBodySchema>

export const MakeWidgetInputSchema = z.object({
  body: WidgetBodySchema,
}).strict()
export type MakeWidgetInput = z.infer<typeof MakeWidgetInputSchema>

export const MakeWidgetOutputSchema = z.object({
  id: z.string(),
  code: z.number().int().optional(),
  location: z.string().optional(),
}).strict()
export type MakeWidgetOutput = z.infer<typeof MakeWidgetOutputSchema>

// ---- Operations interface ----

export interface OutputBindingOperations {
  MakeWidget(input: { body: WidgetBody }, c?: Context<SecurityEnv>): Promise<MakeWidgetOutput>
}

// ---- Middleware interface ----

export interface OutputBindingMiddleware {
  all?: MiddlewareHandler[]
  MakeWidget?: MiddlewareHandler[]
}

// ---- Router factory ----

function _chain(mws: MiddlewareHandler[]): MiddlewareHandler {
  return async (c, next) => {
    let i = 0
    const run = async (): Promise<void> => { i < mws.length ? await mws[i++](c, run) : await next() }
    await run()
  }
}

export function createOutputBindingRouter(ops: OutputBindingOperations, middleware?: OutputBindingMiddleware): Hono {
  const app = new Hono()

  // @http(method: "POST", uri: "/widgets")
  app.post('/widgets',
    _chain([...(middleware?.all ?? []), ...(middleware?.MakeWidget ?? [])]),
    zValidator('json', WidgetBodySchema, (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = { body: c.req.valid('json') }
      try {
        const result = await ops.MakeWidget(input, c as unknown as Context<SecurityEnv>)
        const { code, location, ...__body } = result
        if (location !== undefined) c.header('X-Widget-Location', String(location))
        return c.json(__body, (code ?? 201) as ContentfulStatusCode)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  return app
}
