// DO NOT EDIT — regenerated by smithy-hono on every build

export interface OperationMeta {
  name: string
  description?: string
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'
  path: string
  authSchemes: AuthScheme[]
  readonly: boolean
  streaming?: boolean
  requiredPermissions: string[]
  pagination?: { maxPageSize: number; defaultPageSize: number }
  cost: number
  constraints: { maxBodyBytes?: number; hasConstrainedInput: boolean }
  sensitiveFields?: string[]
  resource?: string
  crudVerb?: 'create' | 'put' | 'read' | 'update' | 'delete' | 'list'
  identifierMembers?: string[]
}

export type AuthScheme =
  | { type: 'oidc' }
  | { type: 'sigv4Hmac' }
  | { type: 'anonymous' }

// ---- Operations ----

export const OPERATIONS: Record<string, OperationMeta> = {
  MakeWidget: {
    name: 'MakeWidget',
    method: 'POST',
    path: '/widgets',
    authSchemes: [{ type: 'anonymous' }],
    readonly: false,
    requiredPermissions: [],
    cost: 1,
    constraints: { hasConstrainedInput: false },
  },
}

// ---- Route index (method + path -> meta) ----

export const OPERATION_BY_ROUTE: Record<string, OperationMeta> = {
  'POST /widgets': OPERATIONS.MakeWidget,
}

