// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import * as _union from './union.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.PutShape, inputSchema: _union.PutShapeInputSchema, outputSchema: _union.PutShapeOutputSchema },
]

export const MCP_PROMPTS = [] as const

