// DO NOT EDIT — regenerated by smithy-hono on every build

import { Hono } from 'hono'
import type { Context, MiddlewareHandler } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'
import type { SecurityEnv } from '@smithy-hono/security-core'

// ---- Schemas ----

export const CircleSchema = z.object({
  radius: z.number().int(),
}).strict()
export type Circle = z.infer<typeof CircleSchema>

export const RectangleSchema = z.object({
  width: z.number().int(),
  height: z.number().int(),
}).strict()
export type Rectangle = z.infer<typeof RectangleSchema>

export const PutShapeInputSchema = z.object({
  shape: z.union([
  z.object({ circle: CircleSchema }).strict(),
  z.object({ rectangle: RectangleSchema }).strict(),
  z.object({ label: z.string() }).strict()
]),
}).strict()
export type PutShapeInput = z.infer<typeof PutShapeInputSchema>

export const PutShapeOutputSchema = z.object({
  shape: z.union([
  z.object({ circle: CircleSchema }).strict(),
  z.object({ rectangle: RectangleSchema }).strict(),
  z.object({ label: z.string() }).strict()
]),
}).strict()
export type PutShapeOutput = z.infer<typeof PutShapeOutputSchema>

// ---- Operations interface ----

export interface UnionOperations {
  PutShape(input: { shape: { circle: Circle } | { rectangle: Rectangle } | { label: string } }, c?: Context<SecurityEnv>): Promise<PutShapeOutput>
}

// ---- Middleware interface ----

export interface UnionMiddleware {
  all?: MiddlewareHandler[]
  PutShape?: MiddlewareHandler[]
}

// ---- Router factory ----

function _chain(mws: MiddlewareHandler[]): MiddlewareHandler {
  return async (c, next) => {
    let i = 0
    const run = async (): Promise<void> => { i < mws.length ? await mws[i++](c, run) : await next() }
    await run()
  }
}

export function createUnionRouter(ops: UnionOperations, middleware?: UnionMiddleware): Hono {
  const app = new Hono()

  // @http(method: "POST", uri: "/shapes")
  app.post('/shapes',
    _chain([...(middleware?.all ?? []), ...(middleware?.PutShape ?? [])]),
    zValidator('json', z.object({
      shape: z.union([
  z.object({ circle: CircleSchema }).strict(),
  z.object({ rectangle: RectangleSchema }).strict(),
  z.object({ label: z.string() }).strict()
]),
    }).strict(), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = { ...c.req.valid('json') }
      try {
        const result = await ops.PutShape(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  return app
}
