// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import * as _playthrough from './playthrough.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.CreatePlaythrough, inputSchema: _playthrough.CreatePlaythroughInputSchema, outputSchema: _playthrough.CreatePlaythroughOutputSchema },
  { op: OPERATIONS.DeletePlaythrough, inputSchema: _playthrough.DeletePlaythroughInputSchema },
  { op: OPERATIONS.GetPlaythrough, inputSchema: _playthrough.GetPlaythroughInputSchema, outputSchema: _playthrough.GetPlaythroughOutputSchema },
  { op: OPERATIONS.ListPlaythroughs, inputSchema: _playthrough.ListPlaythroughsInputSchema, outputSchema: _playthrough.ListPlaythroughsOutputSchema },
  { op: OPERATIONS.UpdatePlaythrough, inputSchema: _playthrough.UpdatePlaythroughInputSchema, outputSchema: _playthrough.UpdatePlaythroughOutputSchema },
]

export const MCP_PROMPTS = [] as const

