// DO NOT EDIT — regenerated by smithy-hono on every build

export const Permissions = {
  PLAYTHROUGHS_WRITE: "playthroughs.write",
  PLAYTHROUGHS_READ: "playthroughs.read",
} as const

export type Permission = typeof Permissions[keyof typeof Permissions]

