// DO NOT EDIT — regenerated by smithy-hono on every build

import { Hono } from 'hono'
import type { Context, MiddlewareHandler } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'
import { authorize } from '@smithy-hono/security-core'
import { OPERATIONS } from './registry.gen'
import type { SecurityEnv, SecurityVariables } from '@smithy-hono/security-core'

// ---- Schemas ----

export const CreatePlaythroughInputSchema = z.object({
  name: z.string(),
  game: z.string(),
}).strict()
export type CreatePlaythroughInput = z.infer<typeof CreatePlaythroughInputSchema>

export const PlaythroughSchema = z.object({
  id: z.string(),
  name: z.string(),
  currentRound: z.number().int().optional(),
}).strict()
export type Playthrough = z.infer<typeof PlaythroughSchema>

export const CreatePlaythroughOutputSchema = z.object({
  playthrough: PlaythroughSchema,
}).strict()
export type CreatePlaythroughOutput = z.infer<typeof CreatePlaythroughOutputSchema>

export const DeletePlaythroughInputSchema = z.object({
  id: z.string(),
}).strict()
export type DeletePlaythroughInput = z.infer<typeof DeletePlaythroughInputSchema>

export const GetPlaythroughInputSchema = z.object({
  id: z.string(),
}).strict()
export type GetPlaythroughInput = z.infer<typeof GetPlaythroughInputSchema>

export const GetPlaythroughOutputSchema = z.object({
  playthrough: PlaythroughSchema,
}).strict()
export type GetPlaythroughOutput = z.infer<typeof GetPlaythroughOutputSchema>

export const ListPlaythroughsInputSchema = z.object({
  filter: z.string().optional(),
  limit: z.number().int().min(1).max(50).optional(),
  nextToken: z.string().optional(),
}).strict()
export type ListPlaythroughsInput = z.infer<typeof ListPlaythroughsInputSchema>

export const ListPlaythroughsOutputSchema = z.object({
  items: z.array(PlaythroughSchema),
  nextToken: z.string().optional(),
}).strict()
export type ListPlaythroughsOutput = z.infer<typeof ListPlaythroughsOutputSchema>

export const UpdatePlaythroughInputSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  currentRound: z.number().int().optional(),
}).strict()
export type UpdatePlaythroughInput = z.infer<typeof UpdatePlaythroughInputSchema>

export const UpdatePlaythroughOutputSchema = z.object({
  playthrough: PlaythroughSchema,
}).strict()
export type UpdatePlaythroughOutput = z.infer<typeof UpdatePlaythroughOutputSchema>

// ---- Errors ----

export class ValidationException extends Error {
  readonly $statusCode = 400
  readonly $fault = 'client' as const
  constructor(message: string) {
    super(message)
    this.name = 'ValidationException'
    Object.setPrototypeOf(this, ValidationException.prototype)
  }
}

export class NotFoundError extends Error {
  readonly $statusCode = 404
  readonly $fault = 'client' as const
  constructor(message: string) {
    super(message)
    this.name = 'NotFoundError'
    Object.setPrototypeOf(this, NotFoundError.prototype)
  }
}

// ---- Operations interface ----

export interface PlaythroughOperations {
  CreatePlaythrough(input: { name: string; game: string }, c?: Context<SecurityEnv>): Promise<CreatePlaythroughOutput>
  DeletePlaythrough(input: { id: string }, c?: Context<SecurityEnv>): Promise<void>
  GetPlaythrough(input: { id: string }, c?: Context<SecurityEnv>): Promise<GetPlaythroughOutput>
  ListPlaythroughs(input: { filter?: string; limit?: number; nextToken?: string }, c?: Context<SecurityEnv>): Promise<ListPlaythroughsOutput>
  UpdatePlaythrough(input: { id: string; name?: string; currentRound?: number }, c?: Context<SecurityEnv>): Promise<UpdatePlaythroughOutput>
}

// ---- Env type ----

export type PlaythroughEnv = { Variables: SecurityVariables }

// ---- Middleware interface ----

export interface PlaythroughMiddleware {
  all?: MiddlewareHandler[]
  CreatePlaythrough?: MiddlewareHandler[]
  DeletePlaythrough?: MiddlewareHandler[]
  GetPlaythrough?: MiddlewareHandler[]
  ListPlaythroughs?: MiddlewareHandler[]
  UpdatePlaythrough?: MiddlewareHandler[]
}

// ---- Router factory ----

function _chain(mws: MiddlewareHandler[]): MiddlewareHandler {
  return async (c, next) => {
    let i = 0
    const run = async (): Promise<void> => { i < mws.length ? await mws[i++](c, run) : await next() }
    await run()
  }
}

export function createPlaythroughRouter(ops: PlaythroughOperations, middleware?: PlaythroughMiddleware): Hono {
  const app = new Hono()

  // @http(method: "POST", uri: "/playthroughs")
  // @requiresAuth(permission: "playthroughs.write")
  app.post('/playthroughs',
    _chain([...(middleware?.all ?? []), ...(middleware?.CreatePlaythrough ?? [])]),
    zValidator('json', z.object({
      name: z.string(),
      game: z.string(),
    }).strict(), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    authorize(OPERATIONS.CreatePlaythrough),
    async (c) => {
      const input = { ...c.req.valid('json') }
      try {
        const result = await ops.CreatePlaythrough(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 201)
      } catch (e) {
        if (e instanceof ValidationException)
          return c.json({ code: 'ValidationException', message: e.message }, e.$statusCode)
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  // @http(method: "DELETE", uri: "/playthroughs/{id}")
  // @requiresAuth(permission: "playthroughs.write")
  app.delete('/playthroughs/:id',
    _chain([...(middleware?.all ?? []), ...(middleware?.DeletePlaythrough ?? [])]),
    zValidator('param', z.object({
      id: z.string(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    authorize(OPERATIONS.DeletePlaythrough),
    async (c) => {
      const input = { ...c.req.valid('param') }
      try {
        await ops.DeletePlaythrough(input, c as unknown as Context<SecurityEnv>)
        return c.body(null, 204)
      } catch (e) {
        if (e instanceof ValidationException)
          return c.json({ code: 'ValidationException', message: e.message }, e.$statusCode)
        if (e instanceof NotFoundError)
          return c.json({ code: 'NotFoundError', message: e.message }, e.$statusCode)
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  // @http(method: "GET", uri: "/playthroughs/{id}")
  // @requiresAuth(permission: "playthroughs.read")
  app.get('/playthroughs/:id',
    _chain([...(middleware?.all ?? []), ...(middleware?.GetPlaythrough ?? [])]),
    zValidator('param', z.object({
      id: z.string(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    authorize(OPERATIONS.GetPlaythrough),
    async (c) => {
      const input = { ...c.req.valid('param') }
      try {
        const result = await ops.GetPlaythrough(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        if (e instanceof ValidationException)
          return c.json({ code: 'ValidationException', message: e.message }, e.$statusCode)
        if (e instanceof NotFoundError)
          return c.json({ code: 'NotFoundError', message: e.message }, e.$statusCode)
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  // @http(method: "GET", uri: "/playthroughs")
  app.get('/playthroughs',
    _chain([...(middleware?.all ?? []), ...(middleware?.ListPlaythroughs ?? [])]),
    zValidator('query', z.object({
      filter: z.string().optional(),
      limit: z.string().regex(/^-?\d+$/).transform(Number).pipe(z.number().int().min(1).max(50)).optional(),
      nextToken: z.string().optional(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = { ...c.req.valid('query') }
      try {
        const result = await ops.ListPlaythroughs(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        if (e instanceof ValidationException)
          return c.json({ code: 'ValidationException', message: e.message }, e.$statusCode)
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  // @http(method: "PUT", uri: "/playthroughs/{id}")
  // @requiresAuth(permission: "playthroughs.write")
  app.put('/playthroughs/:id',
    _chain([...(middleware?.all ?? []), ...(middleware?.UpdatePlaythrough ?? [])]),
    zValidator('param', z.object({
      id: z.string(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    zValidator('json', z.object({
      name: z.string().optional(),
      currentRound: z.number().int().optional(),
    }).strict(), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    authorize(OPERATIONS.UpdatePlaythrough),
    async (c) => {
      const input = {
        ...c.req.valid('param'),
        ...c.req.valid('json')
      }
      try {
        const result = await ops.UpdatePlaythrough(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        if (e instanceof ValidationException)
          return c.json({ code: 'ValidationException', message: e.message }, e.$statusCode)
        if (e instanceof NotFoundError)
          return c.json({ code: 'NotFoundError', message: e.message }, e.$statusCode)
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  return app
}
