// DO NOT EDIT — regenerated by smithy-hono on every build

import type { CreatePlaythroughOutput, GetPlaythroughOutput, ListPlaythroughsOutput, UpdatePlaythroughOutput } from './playthrough.gen'
import { ValidationException, NotFoundError } from './playthrough.gen'
import type { FetchLike } from './client-runtime.gen'
import { SmithyError } from './errors'

// ---- Client options ----

export interface PlaythroughClientOptions {
  /** Defaults to globalThis.fetch. In tests pass app.request.bind(app). */
  fetch?: FetchLike
  /** Prepended to every request path (e.g. 'https://api.example.com'). Defaults to ''. */
  baseUrl?: string
  /** Headers merged into every request — cookies / CSRF / signing. Awaited per request. */
  headers?: () => HeadersInit | Promise<HeadersInit>
}

// ---- Client interface ----

export interface PlaythroughClient {
  CreatePlaythrough(input: { name: string; game: string }): Promise<CreatePlaythroughOutput>
  DeletePlaythrough(input: { id: string }): Promise<void>
  GetPlaythrough(input: { id: string }): Promise<GetPlaythroughOutput>
  ListPlaythroughs(input: { filter?: string; limit?: number; nextToken?: string }): Promise<ListPlaythroughsOutput>
  UpdatePlaythrough(input: { id: string; name?: string; currentRound?: number }): Promise<UpdatePlaythroughOutput>
}

// ---- Internal helpers ----

async function _readBody(res: Response): Promise<unknown> {
  const text = await res.text()
  return text ? JSON.parse(text) : undefined
}

function _throwError(status: number, body: unknown): never {
  const b = (body ?? {}) as { code?: string; message?: string; fieldErrors?: unknown }
  const message = b.message
    ?? (b.fieldErrors !== undefined ? 'ValidationException: ' + JSON.stringify(b.fieldErrors) : 'HTTP ' + status)
  switch (b.code) {
    case 'ValidationException': throw new ValidationException(message)
    case 'NotFoundError': throw new NotFoundError(message)
  }
  throw new SmithyError(message, status, status >= 500 ? 'server' : 'client')
}

// ---- Client factory ----

export function createPlaythroughClient(opts: PlaythroughClientOptions = {}): PlaythroughClient {
  const _fetch: FetchLike = opts.fetch ?? globalThis.fetch
  const _base = opts.baseUrl ?? ''
  const _headers = opts.headers ?? (() => ({}))
  return {
    async CreatePlaythrough(input) {
      const headers = new Headers(await _headers())
      headers.set('content-type', 'application/json')
      const res = await _fetch(`${_base}/playthroughs`, { method: 'POST', headers, body: JSON.stringify({ name: input.name, game: input.game }) })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as CreatePlaythroughOutput
    },
    async DeletePlaythrough(input) {
      const headers = new Headers(await _headers())
      const res = await _fetch(`${_base}/playthroughs/${encodeURIComponent(String(input.id))}`, { method: 'DELETE', headers })
      if (!res.ok) _throwError(res.status, await _readBody(res))
    },
    async GetPlaythrough(input) {
      const headers = new Headers(await _headers())
      const res = await _fetch(`${_base}/playthroughs/${encodeURIComponent(String(input.id))}`, { method: 'GET', headers })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as GetPlaythroughOutput
    },
    async ListPlaythroughs(input) {
      const headers = new Headers(await _headers())
      const _q = new URLSearchParams()
      if (input.filter !== undefined) _q.set("filter", String(input.filter))
      if (input.limit !== undefined) _q.set("limit", String(input.limit))
      if (input.nextToken !== undefined) _q.set("nextToken", String(input.nextToken))
      const _qs = _q.toString()
      const res = await _fetch(`${_base}/playthroughs${_qs ? '?' + _qs : ''}`, { method: 'GET', headers })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as ListPlaythroughsOutput
    },
    async UpdatePlaythrough(input) {
      const headers = new Headers(await _headers())
      headers.set('content-type', 'application/json')
      const res = await _fetch(`${_base}/playthroughs/${encodeURIComponent(String(input.id))}`, { method: 'PUT', headers, body: JSON.stringify({ name: input.name, currentRound: input.currentRound }) })
      if (!res.ok) _throwError(res.status, await _readBody(res))
      return (await res.json()) as UpdatePlaythroughOutput
    },
  }
}
