// DO NOT EDIT — regenerated by smithy-hono on every build

export interface OperationMeta {
  name: string
  description?: string
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'
  path: string
  authSchemes: AuthScheme[]
  readonly: boolean
  streaming?: boolean
  requiredPermissions: string[]
  pagination?: { maxPageSize: number; defaultPageSize: number }
  cost: number
  constraints: { maxBodyBytes?: number; hasConstrainedInput: boolean }
  sensitiveFields?: string[]
  resource?: string
  crudVerb?: 'create' | 'put' | 'read' | 'update' | 'delete' | 'list'
  identifierMembers?: string[]
}

export type AuthScheme =
  | { type: 'oidc' }
  | { type: 'sigv4Hmac' }
  | { type: 'anonymous' }

// ---- Operations ----

export const OPERATIONS: Record<string, OperationMeta> = {
  CreatePlaythrough: {
    name: 'CreatePlaythrough',
    method: 'POST',
    path: '/playthroughs',
    authSchemes: [{ type: 'oidc' }],
    readonly: false,
    requiredPermissions: ["playthroughs.write"],
    cost: 5,
    constraints: { hasConstrainedInput: false },
  },
  DeletePlaythrough: {
    name: 'DeletePlaythrough',
    method: 'DELETE',
    path: '/playthroughs/:id',
    authSchemes: [{ type: 'oidc' }],
    readonly: false,
    requiredPermissions: ["playthroughs.write"],
    cost: 1,
    constraints: { hasConstrainedInput: false },
  },
  GetPlaythrough: {
    name: 'GetPlaythrough',
    method: 'GET',
    path: '/playthroughs/:id',
    authSchemes: [{ type: 'oidc' }],
    readonly: true,
    requiredPermissions: ["playthroughs.read"],
    cost: 1,
    constraints: { hasConstrainedInput: false },
  },
  ListPlaythroughs: {
    name: 'ListPlaythroughs',
    method: 'GET',
    path: '/playthroughs',
    authSchemes: [{ type: 'anonymous' }],
    readonly: true,
    requiredPermissions: [],
    pagination: { maxPageSize: 50, defaultPageSize: 25 },
    cost: 1,
    constraints: { hasConstrainedInput: true },
  },
  UpdatePlaythrough: {
    name: 'UpdatePlaythrough',
    method: 'PUT',
    path: '/playthroughs/:id',
    authSchemes: [{ type: 'oidc' }],
    readonly: false,
    requiredPermissions: ["playthroughs.write"],
    cost: 1,
    constraints: { hasConstrainedInput: false },
  },
}

// ---- Route index (method + path -> meta) ----

export const OPERATION_BY_ROUTE: Record<string, OperationMeta> = {
  'POST /playthroughs': OPERATIONS.CreatePlaythrough,
  'DELETE /playthroughs/:id': OPERATIONS.DeletePlaythrough,
  'GET /playthroughs/:id': OPERATIONS.GetPlaythrough,
  'GET /playthroughs': OPERATIONS.ListPlaythroughs,
  'PUT /playthroughs/:id': OPERATIONS.UpdatePlaythrough,
}

