/**
 * Render a `wrangler.toml` from a {@link DeployConfig} + the resolved deploy
 * context (account id, domain, provisioned resource ids, computed vars). The
 * shape matches the repo's existing hand-written workers (`deploy/cf*`).
 *
 * The load-bearing parts for a same-origin full-stack deploy:
 *   - `routes = [{ pattern, custom_domain = true }]` auto-provisions the DNS
 *     record + edge TLS cert for the domain (apex or subdomain);
 *   - `[assets] run_worker_first = ["<apiPrefix>/*"]` sends API paths to the
 *     Worker BEFORE assets, while `not_found_handling = "single-page-application"`
 *     serves `index.html` for every other (non-asset) path.
 *
 * Secrets are NEVER rendered here — they are bound out-of-band via
 * `wrangler secret put` (see the CLI).
 */
import type { DeployConfig } from './config.js'
import { apiPrefixOf, deriveDurableObjects, REALTIME_HUB_MIGRATION_TAG } from './config.js'

export interface RenderContext {
  accountId: string
  domain: string
  /** binding name → provisioned KV namespace id. */
  kvIds: Record<string, string>
  /** binding name → provisioned D1 database id. */
  d1Ids: Record<string, string>
  /** Computed `[vars]` (config.vars(ctx) merged with OIDC facts). */
  vars: Record<string, string>
}

/** Quote a TOML string value (escape backslash + double-quote). */
function q(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/**
 * Trailing-integer "generation" of a migration tag — `v1`→1, `realtime-v1`→1,
 * `billing-v2`→2. A tag with no trailing digits is generation 1 (the base gen).
 * This is the primary, append-only-stable ordering key for {@link orderMigrationTags}.
 */
export function migrationGeneration(tag: string): number {
  const m = /(\d+)$/.exec(tag)
  return m ? Number(m[1]) : 1
}

/**
 * Order the `[[migrations]]` tag blocks for a rendered `wrangler.toml` so the
 * sequence is APPEND-ONLY STABLE across deploys (R3-1). Cloudflare migration tags
 * are append-only and applied in listed order relative to the account's
 * last-applied tag; if a tag that was already applied ends up rendered BEFORE a
 * never-applied one, wrangler skips (or errors on) the new class → runtime failure.
 *
 * The derived realtime hub tag ({@link REALTIME_HUB_MIGRATION_TAG}) is always
 * injected LAST into the binding array, so ordering by binding-array position lets
 * it "float" to the end and pushes any later-added operator DO before it. Instead
 * we order by:
 *   1. generation ascending — the trailing integer of the tag (see
 *      {@link migrationGeneration}); operator DOs added later use a HIGHER
 *      generation (`v2`, `v3`, …) and therefore always sort AFTER `realtime-v1`
 *      (generation 1), never before it — this is the R3-1 invariant;
 *   2. within one generation, the realtime hub sorts AFTER operator tags, so an
 *      operator's base classes (`v1`) apply before the realtime hub adopted on top
 *      of them (`realtime-v1`), matching the order they were actually applied;
 *   3. first-appearance index as a final, deterministic tiebreak.
 *
 * OPERATOR CONVENTION (documented caveat): keep your initial DO classes in the base
 * generation (`v1`, or any `*-v1` tag); the realtime hub adopts as `realtime-v1` and
 * renders after your `v1` classes. Any DO class you add AFTER adopting realtime must
 * use a HIGHER generation tag (`v2`, `v3`, …) so it renders after `realtime-v1` and
 * the append-only chain stays intact.
 */
export function orderMigrationTags(
  tags: string[],
  firstAppearance: Map<string, number>,
): string[] {
  return [...tags].sort((a, b) => {
    const genDelta = migrationGeneration(a) - migrationGeneration(b)
    if (genDelta !== 0) return genDelta
    const realtimeDelta =
      (a === REALTIME_HUB_MIGRATION_TAG ? 1 : 0) - (b === REALTIME_HUB_MIGRATION_TAG ? 1 : 0)
    if (realtimeDelta !== 0) return realtimeDelta
    return (firstAppearance.get(a) ?? 0) - (firstAppearance.get(b) ?? 0)
  })
}

export function renderWrangler(config: DeployConfig, ctx: RenderContext): string {
  const lines: string[] = []
  const date = config.compatibilityDate ?? '2024-09-23'

  lines.push(`# Generated by @smithy-hono/deploy-cf — DO NOT EDIT BY HAND.`)
  lines.push(`# Re-run \`smithy-hono-deploy <domain>\` to regenerate.`)
  lines.push(`name = ${q(config.appName)}`)
  lines.push(`main = ${q(config.workerEntry)}`)
  lines.push(`compatibility_date = ${q(date)}`)
  lines.push(`account_id = ${q(ctx.accountId)}`)
  lines.push('')

  // Custom domain: auto DNS + edge cert for apex OR subdomain (zone must be active).
  lines.push('routes = [')
  lines.push(`  { pattern = ${q(ctx.domain)}, custom_domain = true },`)
  lines.push(']')
  lines.push('')

  if (config.assets) {
    const prefix = apiPrefixOf(config)
    lines.push('[assets]')
    lines.push(`directory = ${q(config.assets.dir)}`)
    if (config.assets.spa ?? true) {
      lines.push('not_found_handling = "single-page-application"')
    }
    lines.push(`run_worker_first = [${q(`${prefix}/*`)}]`)
    lines.push('')
  }

  for (const kv of config.bindings?.kv ?? []) {
    const id = ctx.kvIds[kv.binding]
    if (!id) throw new Error(`renderWrangler: missing provisioned KV id for binding "${kv.binding}"`)
    lines.push('[[kv_namespaces]]')
    lines.push(`binding = ${q(kv.binding)}`)
    lines.push(`id = ${q(id)}`)
    lines.push('')
  }

  // Operator-declared DOs plus the derived realtime hub (when realtimeHub: true).
  const dos = deriveDurableObjects(config)
  for (const dobj of dos) {
    lines.push('[[durable_objects.bindings]]')
    lines.push(`name = ${q(dobj.name)}`)
    lines.push(`class_name = ${q(dobj.className)}`)
    lines.push('')
  }
  // Group DO classes by migration tag (default v1) into [[migrations]] blocks,
  // rendered in an append-only-STABLE order (R3-1) — NOT binding-array order, which
  // would let the derived realtime tag "float" and corrupt already-applied migration
  // sequences. See orderMigrationTags for the ordering rule + operator convention.
  if (dos.length > 0) {
    const byTag = new Map<string, string[]>()
    const firstAppearance = new Map<string, number>()
    dos.forEach((dobj, i) => {
      const tag = dobj.migrationTag ?? 'v1'
      const arr = byTag.get(tag) ?? []
      arr.push(dobj.className)
      byTag.set(tag, arr)
      if (!firstAppearance.has(tag)) firstAppearance.set(tag, i)
    })
    for (const tag of orderMigrationTags([...byTag.keys()], firstAppearance)) {
      const classes = byTag.get(tag) ?? []
      lines.push('[[migrations]]')
      lines.push(`tag = ${q(tag)}`)
      lines.push(`new_classes = [${classes.map(q).join(', ')}]`)
      lines.push('')
    }
  }

  for (const d1 of config.bindings?.d1 ?? []) {
    const id = ctx.d1Ids[d1.binding]
    if (!id) throw new Error(`renderWrangler: missing provisioned D1 id for binding "${d1.binding}"`)
    lines.push('[[d1_databases]]')
    lines.push(`binding = ${q(d1.binding)}`)
    lines.push(`database_name = ${q(d1.databaseName)}`)
    lines.push(`database_id = ${q(id)}`)
    if (d1.migrationsDir) lines.push(`migrations_dir = ${q(d1.migrationsDir)}`)
    lines.push('')
  }

  const varKeys = Object.keys(ctx.vars)
  if (varKeys.length > 0) {
    lines.push('[vars]')
    for (const k of varKeys) lines.push(`${k} = ${q(ctx.vars[k])}`)
    lines.push('')
  }

  lines.push('[observability]')
  lines.push('enabled = true')
  lines.push('')

  return lines.join('\n')
}
