// DO NOT EDIT — regenerated by smithy-hono on every build

import { z } from 'zod'

// ---- SSE Event Schemas ----

export const GameEndedEventSchema = z.object({
  gameId: z.string(),
  winner: z.string().optional(),
}).strict()
export type GameEndedEvent = z.infer<typeof GameEndedEventSchema>

export const GameStartedEventSchema = z.object({
  gameId: z.string(),
  playerCount: z.number().int(),
}).strict()
export type GameStartedEvent = z.infer<typeof GameStartedEventSchema>

export const PlayerMovedEventSchema = z.object({
  gameId: z.string(),
  playerId: z.string(),
  position: z.string(),
}).strict()
export type PlayerMovedEvent = z.infer<typeof PlayerMovedEventSchema>

// ---- SSE Event Union ----

export type GameEvent =
  | { type: "game:ended"; data: GameEndedEvent }
  | { type: "game:started"; data: GameStartedEvent }
  | { type: "player:moved"; data: PlayerMovedEvent }

// ---- Event Emitter Interface ----

export interface GameEventEmitter {
  emit(channelId: string, event: GameEvent): Promise<void>
}

// ---- Event Source Client ----

export class GameEventSource {
  private readonly es: EventSource
  private readonly handlers = new Map<string, Set<(data: unknown) => void>>()

  constructor(endpoint: string, channelId: string) {
    this.es = new EventSource(`${endpoint}?channelId=${encodeURIComponent(channelId)}`)
    this.es.onmessage = (e) => {
      try {
        const { type, data } = JSON.parse(e.data) as GameEvent
        this.handlers.get(type)?.forEach(h => h(data))
      } catch {}
    }
    const allTypes: GameEvent['type'][] = ["game:ended", "game:started", "player:moved"]
    for (const t of allTypes) {
      this.es.addEventListener(t, (e) => {
        try {
          const data = JSON.parse((e as MessageEvent).data)
          this.handlers.get(t)?.forEach(h => h(data))
        } catch {}
      })
    }
  }

  on<T extends GameEvent['type']>(
    type: T,
    handler: (data: Extract<GameEvent, { type: T }>['data']) => void
  ): () => void {
    if (!this.handlers.has(type)) this.handlers.set(type, new Set())
    this.handlers.get(type)!.add(handler as (data: unknown) => void)
    return () => this.handlers.get(type)?.delete(handler as (data: unknown) => void)
  }

  close(): void { this.es.close() }
}
