// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import { z } from 'zod'
import * as _game from './game.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.Ping, inputSchema: z.object({}).strict(), outputSchema: _game.PingOutputSchema },
]

export const MCP_PROMPTS = [] as const

