// DO NOT EDIT — regenerated by smithy-hono on every build

// MCP tool manifest (Plan 14). Pass MCP_TOOLS + the Hono app to
// createMcpHandler from @smithy-hono/mcp-core to serve this service over MCP.

import { OPERATIONS } from './registry.gen'
import * as _tree from './tree.gen'

export const MCP_TOOLS = [
  { op: OPERATIONS.GetTree, inputSchema: _tree.GetTreeInputSchema, outputSchema: _tree.GetTreeOutputSchema },
]

export const MCP_PROMPTS = [] as const

