// DO NOT EDIT — regenerated by smithy-hono on every build

import { Hono } from 'hono'
import type { Context, MiddlewareHandler } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'
import type { SecurityEnv } from '@smithy-hono/security-core'

// ---- Schemas ----

export const GetTreeInputSchema = z.object({
  id: z.string(),
}).strict()
export type GetTreeInput = z.infer<typeof GetTreeInputSchema>

export type TreeNode = {
  id: string;
  label: string;
  children?: TreeNode[];
}
export const TreeNodeSchema: z.ZodType<TreeNode> = z.lazy(() => z.object({
  id: z.string(),
  label: z.string(),
  children: z.array(TreeNodeSchema).optional(),
}).strict())

export const GetTreeOutputSchema = z.object({
  root: TreeNodeSchema,
}).strict()
export type GetTreeOutput = z.infer<typeof GetTreeOutputSchema>

// ---- Operations interface ----

export interface TreeOperations {
  GetTree(input: { id: string }, c?: Context<SecurityEnv>): Promise<GetTreeOutput>
}

// ---- Middleware interface ----

export interface TreeMiddleware {
  all?: MiddlewareHandler[]
  GetTree?: MiddlewareHandler[]
}

// ---- Router factory ----

function _chain(mws: MiddlewareHandler[]): MiddlewareHandler {
  return async (c, next) => {
    let i = 0
    const run = async (): Promise<void> => { i < mws.length ? await mws[i++](c, run) : await next() }
    await run()
  }
}

export function createTreeRouter(ops: TreeOperations, middleware?: TreeMiddleware): Hono {
  const app = new Hono()

  // @http(method: "GET", uri: "/tree/{id}")
  app.get('/tree/:id',
    _chain([...(middleware?.all ?? []), ...(middleware?.GetTree ?? [])]),
    zValidator('param', z.object({
      id: z.string(),
    }), (result, c) => {
      if (!result.success)
        return c.json({ code: 'ValidationException', fieldErrors: result.error.issues.map(i => ({ path: i.path.join('.'), code: i.code })) }, 400)
    }),
    async (c) => {
      const input = { ...c.req.valid('param') }
      try {
        const result = await ops.GetTree(input, c as unknown as Context<SecurityEnv>)
        return c.json(result, 200)
      } catch (e) {
        return c.json({ code: 'InternalServerError', message: 'Internal server error' }, 500)
      }
    }
  )

  return app
}
