// @ts-check
// Autogenerated sidebar driven by `_category_.json` files + `sidebar_position`
// frontmatter in the `../docs` content root.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
